### ISSUE TITLE
Can't execute a mutation when it's nested inside an object

### ISSUE THREAD

**Issue by folivi** [zino-hofmann/graphql-flutter#1009]
Hi all,
Running mutation fails when the mutation is inside a container object.

On my backend, all the queries are organized by business model. 
We have something like 

mutation {
   business_object {
     mutation1,
     mutation2,   
   }
}

While this seems to be not an issue for graphiql, executing the mutations or queries with parameters fail.
Is there any way to fix/ workaround this issue?

Thank you

**To Reproduce**

```
mutation {
  profiles{
    createProfile(profileData: {
      firstname: "john",
      lastname: "doe"
    }){id}
  }
}

```

The equivalent graphql raw query string:

```
const createProfileMutation = r'''
  mutation {
    createProfile(
      $firstname: String!, 
      $lastname: String!, 
      
    ){
      action: createProfile(createProfileInput: 
      {
        firstname: $firstname,
        lastname: $lastname, 
        
        })
        {
          id,
          firstname,
          lastname,          
        }
  }
  
''';
```

Trying to execute that mutation raised the following exception

> [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Error on line 3, column 7: Expected an argument name
>   ╷
> 3 │       $firstname: String!,
>   │       ^
>   ╵
> 

**Expected behavior**

The request should execute and return the following:

```
{
  "data": {
    "profiles": {
      "createProfile": {
        "id": "ObjectId(\"61e1a68ba90fd9635df5b497\")"
      }
    }
  }
}

```

**device / execution context**
Are you on iOS, android, web, in a simulator, running from the terminal etc? This is especially important for `localhost` connection issues.

### Other useful/optional fields

Please fill or delete these sections if you don't fill them in

<details>
  <summary>Stacktrace:</summary>

```dart
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Error on line 3, column 7: Expected an argument name
  ╷
3 │       $firstname: String!,
  │       ^
  ╵
#0      _Parser._expectToken
package:gql/…/language/parser.dart:61
#1      _Parser._parseName
package:gql/…/language/parser.dart:537
#2      _Parser._parseArgument
package:gql/…/language/parser.dart:429
#3      _Parser._parseNonConstArgument
package:gql/…/language/parser.dart:426
#4      _Parser._parseMany
package:gql/…/language/parser.dart:117
#5      _Parser._maybeParseMany
package:gql/…/language/parser.dart:130
#6      _Parser._parseArguments
package:gql/…/language/parser.dart:418
#7      _Parser._parseField
package:gql/…/language/parser.dart:519
```

</details>

**Comment by budde377** [comment]
@folivi thanks for reaching out, it looks like it's a parse error, which would indicate that your mutation is malformed. We don't have a concept of raw queries, so this might be the source of your error.

**Comment by folivi** [comment]
hi @budde377 
thank you for your answer but unfortunately I think it's worth digging into the parser as the following mutation works when the mutation is not nested

I've been using the package for over a year now and I've always been using it by passing a query string to the mutate or query methods.

The following mutation works fine:
```
const createProfileMutation = r'''
  mutation createProfile(
      $firstname: String!, 
      $lastname: String!, 

    ){
      action: createProfile(createProfileInput: 
      {
        firstname: $firstname,
        lastname: $lastname, 

        })
        {
          firstname,
          lastname,
        }
  }
''';

```

The query is being executed like so:

```
Future<QueryResult> executeMutation(mutation, variable) async {
  final GraphQLClient _client = await graphqlClient();
  final MutationOptions _options =
      MutationOptions(document: gql(mutation), variables: variable);
  final response = await _client.mutate(_options);
  return response;
}


```
This works perfectly. But for a better lisibility my organization groups queries and mutations.

**Comment by budde377** [comment]
Let me try and see if I can reproduce it, but in the meantime, have you tried looking at the gql project? We're using their parser

**Comment by folivi** [comment]
I'll take a look. But this package has been doing the job till now :)
It would be amazing to find a fix/workaround as grouping queries helps a lot when dealing with huge apis

**Comment by budde377** [comment]
@folivi, I've tried to reproduce your error in this test: [packages/graphql/test/parse_test.dart](https://github.com/zino-hofmann/graphql-flutter/blob/805b97000a256853f108ca124449f663f5bc2839/packages/graphql/test/parse_test.dart). The test runs and parses successfully. "Nesting" mutations should really not make any difference. The client doesn't care and adding variables to nested objects is certainly supported. 

I can look into this more if you have a reproducible example! Again, parse errors are most likely due to errors in the `gql` library, which is another library.

**Comment by folivi** [comment]
hi again.
thank you for your efforts

You should test with the following query string instead:

```
r'''
  mutation profiles {
    createProfile(
      $firstname: String!, 
      $lastname: String!, 
    ){
      action: createProfile(createProfileInput: 
      {
        firstname: $firstname,
        lastname: $lastname, 
        })
        {
          firstname,
          lastname,
        }
  }
  }
'''
```

note the _profiles { }_

**Comment by budde377** [comment]
Thanks for elaborating @folivi! That is not valid GraphQL, see the spec [here](https://spec.graphql.org/October2021/#sel-DAFfDPAACRA-H)

> Variables must be defined at the top of an operation and are in scope throughout the execution of that operation. Values for those variables are provided to a GraphQL service as part of a request so they may be substituted in during execution.

GraphiQL [here](https://graphql.org/swapi-graphql?query=%20%20mutation%20profiles%20%7B%0A%20%20%20%20createProfile(%0A%20%20%20%20%20%20%24firstname%3A%20String!%2C%20%0A%20%20%20%20%20%20%24lastname%3A%20String!%2C%20%0A%20%20%20%20)%7B%0A%20%20%20%20%20%20action%3A%20createProfile(createProfileInput%3A%20%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20firstname%3A%20%24firstname%2C%0A%20%20%20%20%20%20%20%20lastname%3A%20%24lastname%2C%20%0A%20%20%20%20%20%20%20%20%7D)%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20firstname%2C%0A%20%20%20%20%20%20%20%20%20%20lastname%2C%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%7D%0A%20%20%7D%0A) doesn't agree either 

<img width="397" alt="Screenshot 2022-01-16 at 21 35 24" src="https://user-images.githubusercontent.com/3490507/149678982-2471146e-f3dc-4cc0-b7d0-029a781c4ea2.png">

I am not familiar with this dialect, but if you want it supported you should raise this issue on https://github.com/gql-dart/gql as it would need to be supported by their parser (and subsequently your server).

**Comment by folivi** [comment]
Hi,

here is a way to make it work:


const createProfileMut = r'''
  mutation createProfile($firstname: String!, $lastname: String!) {
    profiles {
      createProfile(
      profileData: {
        firstname: $firstname,
        lastname: $lastname,
      }
    ) {
      id,
    }
    }
  }
''';

I hope it helps someone.

Thank you again @budde377 for your time
