### ISSUE TITLE
Query call to server three times

### ISSUE THREAD

**Issue by dasarijit88** [zino-hofmann/graphql-flutter#1011]
**Describe the issue**
The Query Widget call to server three times.

**To Reproduce (MUST BE PROVIDED)**

Please find my code below

`class HomeAuth extends StatelessWidget {
@OverRide
Widget build(BuildContext context) {
return Config.config(param: HomeAuthTabScreen());
}
}

class HomeAuthTabScreen extends StatefulWidget {

@OverRide
_HomeAuthTabScreenState createState() => _HomeAuthTabScreenState();
}

class _HomeAuthTabScreenState extends State {

}

final String _query = """
query getData{
Student {
name
id
address {
city
street
number
zipCode
}
}

""";

@OverRide
Widget build(
BuildContext context,
) {

print("Before Query is fired");
return Container(
  color: Colors.white
  child: 
  Query(
      options: QueryOptions(
        document: gql(_query),
      ),
      builder: (QueryResult result,
          {VoidCallback refetch, FetchMore fetchMore})   {
        if (result.hasException) {
          print(result.exception);

        }
        if (result.isLoading) {
          return Center(child: CupertinoActivityIndicator());
        }
print("After Query is fired");

        return 
         
             Container(child: Center(child: Text("Testing")));
            
       
      }),
          );
}
}`

**Expected behavior**
Call one time to the server

**device / execution context**
Tested on ios devices . It happens both in emulator and real devices. I am using graphql_flutter version 5.0.1-beta.3

**Comment by vincenzopalazzo** [comment]
Hi, Can you provide a code well format? with flutter, it is pretty easy to have code formatted.

In addition, you code it is not executable, we need a minimal reproducible example, otherwise, you need to wait that we need to reproduce it.

**Comment by dasarijit88** [comment]
@vincenzopalazzo - Here you go

```

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:graphql_flutter/graphql_flutter.dart';
import 'package:provider/provider.dart';
import 'config.dart';
import 'providers/auth.dart';
import 'screens/auth_screen.dart';
import 'screens/home.dart';
import 'screens/splash_screen.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await initHiveForFlutter();

  MainScreen();

  runApp(MultiProvider(providers: [
    ChangeNotifierProvider<Auth>(create: (_) => Auth()),
  ], child: MainScreen()));
}

class MainScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Consumer<Auth>(builder:
        (final BuildContext context, final Auth auth, final Widget child) {
      return MaterialApp(
          title: 'MyApp',
          debugShowCheckedModeBanner: false,
          theme: ThemeData(
              primarySwatch: Colors.green,
              visualDensity: VisualDensity.adaptivePlatformDensity),
          initialRoute: '/',
          routes: {
            '/auth': (context) => AuthScreen(),
            '/main': (context) => MainScreen(),
            '/home': (context) => HomeScreen(),
            '/homeauth': (context) => HomeAuth(),
          },
          home: auth.isAuth
              ? HomeAuth()
              : FutureBuilder(
                  future: auth.tryAutoLogin(),
                  builder: (ctx, authResultSnapshot) =>
                      authResultSnapshot.connectionState ==
                              ConnectionState.waiting
                          ? SplashScreen()
                          : AuthScreen(),
                ));
    });
  }
}

class HomeAuth extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Config.config(param: HomeAuthTabScreen());
  }
}

class HomeAuthTabScreen extends StatefulWidget {
  static String accessTip;
  static String keysTip;
  @override
  _HomeAuthTabScreenState createState() => _HomeAuthTabScreenState();
}

class _HomeAuthTabScreenState extends State<HomeAuthTabScreen> {
  final String _query = """
query getData{
Student {
name
id
address {
city
street
number
zipCode
}
}

""";

  @override
  Widget build(
    BuildContext context,
  ) {
    print("Before Query is fired");
    return Container(
      color: AuthScreen.backgroundColor,
      child: Query(
          options: QueryOptions(
            document: gql(_query),
          ),
          builder: (QueryResult result,
              {VoidCallback refetch, FetchMore fetchMore}) {
            if (result.hasException) {
              print(result.exception);
              return AuthScreen();
            }
            if (result.isLoading) {
              return Center(child: CupertinoActivityIndicator());
            }

            print("After Query is fired");

            return Material(
                child: Container(child: Center(child: Text("Testing"))));
          }),
    );
  }
}


```

**Comment by dasarijit88** [comment]
The following NoSuchMethodError was thrown building StreamBuilder<QueryResult>(dirty, state:
_StreamBuilderBaseState<QueryResult, AsyncSnapshot<QueryResult>>#73383):
The method '[]' was called on null.
Receiver: null


Also I keep getting this error , previously the below code used to work and till the time the query is fetched a loading indicator used to display in screen but now the data is loaded without loading indicator and the above error

```
  if (result.isLoading) {
              
                        return Center(child: CupertinoActivityIndicator());
                      }
```

**Comment by budde377** [comment]
The fact that the builder is called does not mean that there's been a network request. When the cache is re-broadcasted, the appropriate build methods should be called. Are you absolutely certain that the request is actually called three times?

**Comment by chinitadelrey** [comment]
@budde377 Do you or anyone knows if there is an option to automatically log every query/mutation etc to console when it is being done? I think I have seen it before but not sure how to do it. 

I'm having an issue with a separate problem and want to know exactly what is being sent to the server. Might help OP in checking this as well.

**Comment by vincenzopalazzo** [comment]
>@budde377 Do you or anyone knows if there is an option to automatically log every query/mutation etc to console when it is being done? I think I have seen it before but not sure how to do it.

unfortunately no :/ but you can open an issue and we can work on this

**Comment by budde377** [comment]
For this, you might en able to implement your own version of a link, just as auth or http links. It's probably the easiest way to log network requests and give you full control of what's logged considering api keys etc.

**Comment by vincenzopalazzo** [comment]
I was unable to reproduce this, so I will close until we have a good example that reproduce the problem and help us to fix the bug
