### ISSUE TITLE
Type parameter parserFn is required  when constructing options.

### ISSUE THREAD

**Issue by renancaraujo** [zino-hofmann/graphql-flutter#1052]
**Describe the issue**
`SubscriptionOptions`, `QueryOptions` and `MutationOptions` have contructors with an optional `parserFn` parameter and a type parameter `TParsed` . 

When the user desires to  omit   `parserFn`, `TParsed` is still required, even though the existence of `TParsed` without a `parserFn` serves no purpose.

This creates an error:
```dart
MutationOptions(
    document: gql(_rawQuery),
    operationName: 'Something something',
    variables: <String, dynamic>{
      'input': {
        'stuff': 42,
      },
    },
  )
```

A workaround is to pass void as type param:

```dart
MutationOptions<void>(
    document: gql(_rawQuery),
    operationName: 'Something something',
    variables: <String, dynamic>{
      'input': {
        'stuff': 42,
      },
    },
  )
```

For a more consistent API, one can make the type parameter optional by specifying a supertype for `TParsed`: 

```diff
- class MutationOptions<TParsed> extends BaseOptions<TParsed> {
+ class MutationOptions<TParsed extends Object?> extends BaseOptions<TParsed> {
```

In this way, `TParsed` doesn't ever need to be explicitly passed. 

```dart
MutationOptions(
    document: gql(_rawQuery),
    operationName: 'Something something',
    variables: <String, dynamic>{
      'input': {
        'stuff': 42,
      },
    },
  )
```

**To Reproduce (MUST BE PROVIDED)**
Just use this package creating either `SubscriptionOptions`, `QueryOptions` or `MutationOptions` omitting `parserFn`.

**Expected behavior**
`TParsed` should not be a required argument if `parserFn` isn't.

**device / execution context**
This does not regard any specific device constraint.

**Comment by budde377** [comment]
@renancaraujo, in my code, the variables is defaulted to `dynamic`. Do you know why this is not the case in yours? A different language version?

**Comment by renancaraujo** [comment]
This is visible to projects that sets `implicit-dynamic` to false in the analyzer file.

**Comment by budde377** [comment]
@renancaraujo, just so we're on the same page. That'd be the `strict-raw-types`?

**Comment by budde377** [comment]
@renancaraujo, can you please check out this PR to see if this solves your issue: #1053

**Comment by babou360** [comment]
I'm some issues with subscription while accessing client directly without subscription widget
