### ISSUE TITLE
UUIDs/ID aren't formatted properly

### ISSUE THREAD

**Issue by widavies** [zino-hofmann/graphql-flutter#1059]
**Describe the issue**
When querying an ID type (backed by UUID), it seems as though the dashes are removed
```
// Correct
9dc1c7e8-6878-4116-bbd8-92ae25566934
// Returned from GraphQL-Flutter
9dc1c7e868784116bbd892ae25566934
```

Would it be possible to keep the dashes?

(In my specific case I'm using C# GraphQL library Hot Chocolate)

**Comment by budde377** [comment]
I'd be very surprised if the client is performing any kind of manipulation of the returned result. We don't treat IDs any different.

Can you check your serialisation framework and double check the network result?

**Comment by widavies** [comment]
Ah yeah you're right, sorry about that. Somehow certain GraphQL requests return weird Ids and not others. Thanks!
