### ISSUE TITLE
Error: Read-only file system

### ISSUE THREAD

**Issue by anmolgupta-aeologic** [zino-hofmann/graphql-flutter#1062]
E/flutter (12991): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Creation failed, path = 'my' (OS Error: Read-only file system, errno = 30)
E/flutter (12991): #0      _Directory.create.<anonymous closure> (dart:io/directory_impl.dart:117:11)
E/flutter (12991): #1      _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (12991): #2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (12991): <asynchronous suspension>
E/flutter (12991): #3      BackendManager.open (package:hive/src/backend/vm/backend_manager.dart:21:7)
E/flutter (12991): <asynchronous suspension>
E/flutter (12991): #4      HiveImpl._openBox (package:hive/src/hive_impl.dart:100:15)
E/flutter (12991): <asynchronous suspension>
E/flutter (12991): #5      HiveImpl.openBox (package:hive/src/hive_impl.dart:139:12)
E/flutter (12991): <asynchronous suspension>
E/flutter (12991): #6      HiveStore.open (package:graphql/src/cache/hive_store.dart:26:17)
E/flutter (12991): <asynchronous suspension>
E/flutter (12991): #7      _SignUpScreenState.getClient (package:jungle_x/src/view/screens/auth/signup.dart:34:19)
E/flutter (12991): <asynchronous suspension>
E/flutter (12991): 
E/flutter (12991): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Creation failed, path = 'my' (OS Error: Read-only file system, errno = 30)
E/flutter (12991): #0      _Directory.create.<anonymous closure> (dart:io/directory_impl.dart:117:11)
E/flutter (12991): #1      _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (12991): #2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (12991): <asynchronous suspension>
E/flutter (12991): #3      BackendManager.open (package:hive/src/backend/vm/backend_manager.dart:21:7)
E/flutter (12991): <asynchronous suspension>
E/flutter (12991): #4      HiveImpl._openBox (package:hive/src/hive_impl.dart:100:15)
E/flutter (12991): <asynchronous suspension>
E/flutter (12991): #5      HiveImpl.openBox (package:hive/src/hive_impl.dart:139:12)
E/flutter (12991): <asynchronous suspension>
E/flutter (12991): #6      HiveStore.open (package:graphql/src/cache/hive_store.dart:26:17)
E/flutter (12991): <asynchronous suspension>
E/flutter (12991): #7      _SignUpScreenState.getClient (package:jungle_x/src/view/screens/auth/signup.dart:34:19)
E/flutter (12991): <asynchronous suspension>
E/flutter (12991):

**Comment by budde377** [comment]
Looking at your stacktrace it looks to be because you're using hive. Please consider using another cache, e.g. in memory.
