### ISSUE TITLE
'QueryResult<dynamic>' is not a subtype of type 'QueryResult<Tickets$Query>' of 'result' while using poll interval

### ISSUE THREAD

**Issue by vasilich6107** [zino-hofmann/graphql-flutter#1072]
I had some errors in console while using `pollInterval`

```
flutter: Caught error: type 'QueryResult<dynamic>' is not a subtype of type 'QueryResult<Tickets$Query>' of 'result'
flutter: #0      ObservableQuery.addResult (package:graphql/src/core/observable_query.dart)
#1      QueryManager.addQueryResult (package:graphql/src/core/query_manager.dart:393:23)
#2      QueryManager._resolveQueryOnNetwork (package:graphql/src/core/query_manager.dart:265:7)
<asynchronous suspension>
```

**To Reproduce**
I tried to fix the issues quickly with #1071 PR but the fix was not reliable (see comment https://github.com/zino-hofmann/graphql-flutter/pull/1071#discussion_r828302466)
Unfortunately I have no time to continue so I reverted back to v5.0.0

**Expected behavior**
No errors in console

**Comment by vincenzopalazzo** [comment]
Thanks! I will try to reproduce and write a test of it to avoid future problems.

I will take your PR as a base, thanks to report it!

**Comment by budde377** [comment]
@vincenzopalazzo If you have enough on your plate with the change log fix and release, I can pick this up.

**Comment by vincenzopalazzo** [comment]
Of curse :) This PR introduce a good solution https://github.com/zino-hofmann/graphql-flutter/pull/1073 I will help in the review when it is completed

**Comment by vincenzopalazzo** [comment]
for the end of the week we try to make a new beta release to test this functionality
