### ISSUE TITLE
Add interceptors in flutter_graphql to use refresh token to get new access token.

### ISSUE THREAD

**Issue by ShourovRoy** [zino-hofmann/graphql-flutter#1083]
Add interceptors in flutter_graphql to use refresh token to get new access token. There is no official solution for using a refresh token in flutter with graphql. Please add this feature in the next version.

**Comment by budde377** [comment]
I don't think this is a good idea to implement this as part of the client. You can implement this as a separate link. Furthermore, I'm not totally convinced such a link should be part of this package. It'll increase the amount of code we'll have to maintain and the general usability is questionable.

**Comment by vincenzopalazzo** [comment]
>I'm not totally convinced such a link should be part of this package. It'll increase the amount of code we'll have to maintain and the general usability is questionable.

I agree with this idea! We use an external package to manage the link! However, a new package like `graphql_links` can be welcome to see around
