### ISSUE TITLE
Graphql_flutter query result not coming in desired format extra __typename is coming from server

### ISSUE THREAD

**Issue by manjeety87** [zino-hofmann/graphql-flutter#1087]
{__typename: DummyStockData, title: nifty, subtitleData: 0.86(1.25%), subtitle: nse, titleData: 98.65, graphData: [{__typename: GraphData, srno: 0, data: 50}, {__typename: GraphData, srno: 1, data: 80}, {__typename: GraphData, srno: 2, data: 90}, {__typename: GraphData, srno: 3, data: 70}, {__typename: GraphData, srno: 4, data: 100}, {__typename: GraphData, srno: 5, data: 80}, {__typename: GraphData, srno: 6, data: 70}, {__typename: GraphData, srno: 7, data: 120}, {__typename: GraphData, srno: 8, data: 100}, {__typename: GraphData, srno: 9, data: 140}]}

The output I want is in json format 

{
     DummyStockData: title: nifty, subtitleData: 0.86(1.25%), subtitle: nse, titleData: 98.65
     graphData: [
{srno: 0, data: 50},{srno: 2, data: 90}, { srno: 3, data: 70}, { srno: 4, data: 100}, {srno: 5, data: 80}, { srno: 6, data: 70}, {srno: 7, data: 120}, {srno: 8, data: 100}, {srno: 9, data: 140}
]
}

why there extra data like __typename is coming ?
DummyStockData is a object in which graphData is array of objects

My Code : 
`class QueryExample extends StatelessWidget {
  final String getMission = r"""
                   query MyQuery {
  getDummyStockData {
    title
    subtitleData
    subtitle
    titleData
    graphData {
srno      
data
    }
  }
}
                  """;
  const QueryExample({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("GraphlQL Client"),
      ),
      body: Query(
        options: QueryOptions(
          document: gql(getMission),
        ),
        builder: (QueryResult result,
            {VoidCallback? refetch, FetchMore? fetchMore}) {
          if (result.hasException) {
            return Text(result.exception.toString());
          }

          if (result.isLoading) {
            return const Text('Loading');
          }

          if (result.data != null) {
            const Text("Sucess");
          }
          // ignore: unused_local_variable
          var counters = result.data!['getDummyStockData'];
          print('counters $counters');
          return Text(counters.toString());
        },
      ),
    );
  }
} `

How can I change the query result to type dynamic to -
`class SharesCardModel {
  final String title;
  final String subtitle;
  final String titleData;
  final String subtitleData;
  final List<LineGraphData> graphData;
  SharesCardModel({
    required this.title,
    required this.subtitle,
    required this.titleData,
    required this.subtitleData,
    required this.graphData,
  });
}
class LineGraphData {
  final int time;
  final int shares;

  LineGraphData(this.time, this.shares);
}`

**Comment by budde377** [comment]
This is expected behaviour. The gql adds the typename which is used for normalisation.

**Comment by manjeety87** [comment]
> This is expected behaviour. The gql adds the typename which is used for normalisation.

How would I get the data in proper json format so that I can map it down

**Comment by budde377** [comment]
What do you mean? The data is a map parsed from JSON.

**Comment by budde377** [comment]
If you need a json string, you can serialise it back as you'd normally do.
