### ISSUE TITLE
Error Add dependencies 

### ISSUE THREAD

**Issue by Tanvirul-swe** [zino-hofmann/graphql-flutter#1102]
```
Running "flutter pub get" in gql...                             
Because graphql_flutter >=5.1.0 depends on graphql ^5.1.0 which depends on gql ^0.13.0, graphql_flutter >=5.1.0 requires gql ^0.13.0.
So, because gql depends on graphql_flutter ^5.1.0 and gql is 1.0.0+1, version solving failed.
pub get failed (1; So, because gql depends on graphql_flutter ^5.1.0 and gql is 1.0.0+1, version solving failed.)
```

**Comment by vincenzopalazzo** [comment]
@Tanvirul-swe can you upload the pubspec.yaml?


This error looks client-related and not from us

**Comment by Tanvirul-swe** [comment]
> @Tanvirul-swe can you upload the pubspec.yaml?
> 
> This error looks client-related and not from us

name: gql
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter  
  graphql_flutter: ^5.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by vincenzopalazzo** [comment]
@Tanvirul-swe can you try to change the name of your project? from `gql` to `gql_app`?

There is an dependence called `gql` and dart got confused

**Comment by Tanvirul-swe** [comment]
> 

You are right. After the change of project name, it works properly.Thanks
