### ISSUE TITLE
GraphQL client rich enhancement for request retry, connectivity change interceptors, etc for user engagements.

### ISSUE THREAD

**Issue by muhsinzyne** [zino-hofmann/graphql-flutter#1107]
** Kindly advise me if there is a possible way same like in the Flutter Dio package to add interceptors like connectivity retry, on connection change, global error handler interceptors etc for a better network communication  **

**Same like in Flutter Dio package**

**Comment by budde377** [comment]
Check out the dio http link: https://pub.dev/packages/gql_dio_link
