### ISSUE TITLE
there is a error when upgrade the package to the 5.1.1

### ISSUE THREAD

**Issue by Refaat2020** [zino-hofmann/graphql-flutter#1109]
my previous version 3.10 was working fine but when updated to the current version 
 it returns an error 

OperationException(linkException: ServerException(originalException: null, parsedResponse: Response(data: null, errors: null, context: Context({ResponseExtensions: Instance of 'ResponseExtensions'}), response {error: Unauthorized, message: Access token invalid})), graphqlErrors: [])

**Comment by budde377** [comment]
I would expect upgrading two major versions may break your app. It looks like the error is pretty obvious from your error message, try and have a look at how your links are set up and if the authorisation tokens are properly passed.

**Comment by Refaat2020** [comment]
Please I couldn't find the error so please have a look at my code and tell me where the error could be found 
[https://i.ibb.co/mcvVMPc/screen-1.png](url)

[https://i.ibb.co/Y36sZgf/screen2.png](url)

**Comment by Refaat2020** [comment]
@budde377 
class GraphQLService {
  late GraphQLClient _client;
  GraphQLService() {
    initClient();
  }
  // Setup the apollo client on initialize
  initClient() {
    try {

      String serverUrl = AppUrls.getServerUrl(appFlavor);
      Logger().i("Server Url: $serverUrl");

      final HttpLink _httpLink = HttpLink("$serverUrl/graphql");
      final token = Preference.getString(PrefKeys.accessToken) ?? "";
      Logger().i("graph token: $token");
      //
      final AuthLink _authLink =
          AuthLink(getToken: () async => Preference.getString(PrefKeys.accessToken));
      Link _link = _authLink.concat(_httpLink);
      final GraphQLClient client = GraphQLClient(cache: GraphQLCache(store: InMemoryStore()), link: _link,);
      // readRepositories(client);
      return this._client = client;
    } catch (e) {
      print(e);
      print('error initializing graphql');
    }
  }

  /// Use this for cached queries
  Future<dynamic> query({required String query,  Map<String, dynamic> ?variables}) async {
    final QueryOptions options = QueryOptions(
      document: gql(query),
      variables: variables??{},
      fetchPolicy: FetchPolicy.networkOnly,
    );

    final QueryResult result = await _client.query(options);

    return result.handleResponse();
  }

  /// Use this for mutations
  Future<dynamic> mutate({required String mutation, required Map<String, dynamic> variables}) async {
    final MutationOptions options = MutationOptions(
      fetchPolicy: FetchPolicy.networkOnly,
      document: gql(mutation),
      variables: variables,
    );
    final QueryResult result = await _client.mutate(options);

    return result.handleResponse();
  }
  
}

**Comment by budde377** [comment]
I don't know what kind of token your API requires. Maybe you'll need to prefix your token with `Bearer `? 

I.e.,

```dart
      AuthLink(getToken: () async => "Bearer ${Preference.getString(PrefKeys.accessToken)}");
```

**Comment by vincenzopalazzo** [comment]
>Please I couldn't find the error so please have a look at my code and tell me where the error could be found

@Refaat2020 You are 2 years late, that with software is history! What we suggest is try to follow https://github.com/zino-hofmann/graphql-flutter/blob/main/changelog-v3-v4.md that is easily found in the repository.

If the error persists, take an empty project and start a graph_flutter project from scratch. debugging your code with difference between the new and old version is an easy job more than you are asking to us

**Comment by Davete0302** [comment]
Have you found a solution?
