### ISSUE TITLE
[Please Help]Request Headers Converting to Array

### ISSUE THREAD

**Issue by manuelist** [zino-hofmann/graphql-flutter#1110]
Hello is there a way to convert request headers to non array? Thanks in advance

My expected behavior is.
`x-authid: df3c6255-041f-4df0-86bb-f83504bfc10d`

![Screen Shot 2022-04-22 at 9 26 44 AM](https://user-images.githubusercontent.com/4785751/164579634-833999ec-875d-411a-abf4-2e9c43e578e3.png)

What happening now in my flutter app is the headers is converting into array. 
`x-authid: [df3c6255-041f-4df0-86bb-f83504bfc10d]`

![Screen Shot 2022-04-21 at 9 52 22 PM](https://user-images.githubusercontent.com/4785751/164579668-4e13eaab-4ae9-4912-84b7-f1a5128d4dbf.png)

Here is my sample code

```
 GraphQLClient clientToQuery([String? accessToken]) {
    final httpLinks = HttpLink(
        server,
        defaultHeaders: <String, String>{
          'x-authid': 'df3c6255-041f-4df0-86bb-f83504bfc10d',
        },
      );

      return GraphQLClient(
        cache: GraphQLCache(store: HiveStore()),
        link: httpLinks,
      );
  }
```

**Comment by vincenzopalazzo** [comment]
This looks unrelated to the client, because the header is managed by https://github.com/gql-dart/gql
