### ISSUE TITLE
graphql nested array getdata in flutter

### ISSUE THREAD

**Issue by amosadiv** [zino-hofmann/graphql-flutter#1120]
"""query(\$id:ID){
allSchoolList(id:\$id){
data{
id
  attributes{
    schoolName
    schoolPlace
    schoolImage{
      data{
        id
        attributes{
          url
        }
      }
    }
    class_lists{
      data{
        id
        attributes{
          standard
          section
          studentlists{
            data{
              id
              attributes{
                stuname
                stugrade
              }
            }
          }
        }
      }
    }
    
  }
}
}
}""";

how to get studentlists, stuname,stugrade .   **please help me....**

**Comment by vincenzopalazzo** [comment]
Does this sound like a homework question?
