### ISSUE TITLE
supporting flutter 3

### ISSUE THREAD

**Issue by vincenzopalazzo** [zino-hofmann/graphql-flutter#1134]
This required a little bit of reasoning!

**Comment by fabis94** [comment]
You can support both flutter v2 and v3 using an approach like this:

```dart
```

(source: https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0#your-code)

**Comment by vincenzopalazzo** [comment]
@fabis94 do you like to make a PR, I'm a little bit busy these days! Sorry
