### ISSUE TITLE
Widget testing and Unit Testing examples

### ISSUE THREAD

**Issue by armandojimenez** [zino-hofmann/graphql-flutter#1135]
**Is your feature request related to a problem? Please describe.**
I can't find any information on how to unit and widget test this package, especifically widgets and mocking, there is not any info online or tutorials or examples. Do you guys even do unit testing or widget testing with GraphQL?

**Describe the solution you'd like**
Clear examples on how to widget test with this package.

**Describe alternatives you've considered**
Looking for info or tutorials, there is none.

**Comment by denes16** [comment]
How can i test widgets using the hooks?.

**Comment by vincenzopalazzo** [comment]
Mh I think this is not related to graphql library, you can 
call the server and check what the app contains inside the 
widget after the completition of the call.

In addition, this operation that required the usage of the network 
in flutter require to write integration testing, or you can just
mock the server.
