### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by saltatory** [zino-hofmann/graphql-flutter#1161]
It would be delightful if this package was supported for web. I checked and the dependencies e.g. hive, connectivity_plus, graphql, appear to be supported.

Is there a reason this is not available? What can I do to contributed?

**Comment by budde377** [comment]
It should support web.

**Comment by vincenzopalazzo** [comment]
It is https://lnmetrics.info

**Comment by saltatory** [comment]
It does ... it just was not marked as such on pub.

Thanks for the excellent library.
