### ISSUE TITLE
DateTime is not getting convert to the Graphql Type Date 

### ISSUE THREAD

**Issue by kunalgharate** [zino-hofmann/graphql-flutter#1175]
**Error**

 _RequestFormatException(originalException: Converting object to an encodable object failed: _LinkedHashSet len:1, request: Request(operation: Operation(document: DocumentNode("mutation($country: String!, $insuranceProvider: String!, $memberId: String, $cardNumber: String!, $plan: String!, $validFrom: Date!, $validTo: Date!, $status: String!, $cardImage: String) {\n  __typename\n  createInsurance(patientId: \"10\", content: {country: $country, insuranceProvider: $insuranceProvider, memberId: $memberId, cardNumber: $cardNumber, plan: $plan, validFrom: $validFrom, validTo: $validTo, status: $status, cardImage: $cardImage}) {\n    __typename\n    id\n    patientId\n    country\n    insuranceProvider\n    memberId\n    cardNumber\n    plan\n    validFrom\n    validTo\n    status\n    cardImage\n    createdAt\n    updatedAt\n  }\n}"), operationName: null), variables: {patientId: 10, content: {{{country: dfjsdjfs, insuranceProvider: dsdsjfsjfsng, memberId: Strijdcsjcsng, cardNumber: dvjscvjs, plan: jdjf, validFrom:_ 

**Schema** 

```
mutation ($country: String!, $insuranceProvider: String!, $memberId: String, $cardNumber: String!, $plan: String!, $validFrom: Date!, $validTo: Date!, $status: String!, $cardImage: String) {
  createInsurance(patientId: "10", content: {country: $country, insuranceProvider: $insuranceProvider, memberId: $memberId, cardNumber: $cardNumber, plan: $plan, validFrom: $validFrom, validTo: $validTo, status: $status, cardImage: $cardImage}) {
    id
    patientId
    country
    insuranceProvider
    memberId
    cardNumber
    plan
    validFrom
    validTo
    status
    cardImage
    createdAt
    updatedAt
  }
}
```

```

**// Passing data** 

document: gql(InsuranceSchema.addInsuranceSchema),
        variables: {
          'patientId': '10',
          // 'content': patientInsuranceInput.toJson()
          'content': {
            {
              {
                "country": "dfjsdjfs",
                "insuranceProvider": "dsdsjfsjfsng",
                "memberId": "Strijdcsjcsng",
                "cardNumber": "dvjscvjs",
                "plan": "jdjf",
                "validFrom": graphQLDate.serialize(DateTime.now()),
                "validTo": graphQLDate.serialize(DateTime.now()),
                "status": "jssfj",
                "cardImage": "gsjgsj"
              }
            }
          }
        }));

```

I want to insert date. to the graphql but it's not working with flutter 

<img width="638" alt="ins" src="https://user-images.githubusercontent.com/20945934/177194450-b33162ad-654d-469a-ab9e-ec2311b083a2.png">

**Comment by vincenzopalazzo** [comment]
please provide a more well-format example! it is unreadble

**Comment by kunalgharate** [comment]
@vincenzopalazzo  please check I have the question. if you need more help please let me know

**Comment by kunalgharate** [comment]
@vincenzopalazzo  would you like to help me with Date insertion using mutation I want to know how to insert date

**Comment by vincenzopalazzo** [comment]
the problem in how you pass the string, and also are you sure that you are suing `graphql_flutter`? if yes, please check how we pass the variable!

**Comment by vincenzopalazzo** [comment]
https://github.com/zino-hofmann/graphql-flutter/tree/main/packages/graphql

**Comment by vincenzopalazzo** [comment]
NP. in your query parameter there is no `content` variable.

I'm going to close this issue, if you have a complete example that I can reproduce I'm happy to help!

Otherwise if you a seeking help try discord or github discussion
