### ISSUE TITLE
Improve fragment methods and normalisation

### ISSUE THREAD

**Issue by budde377** [zino-hofmann/graphql-flutter#1176]
The fragment api is awkward especially with fragments on queries etc. I believe there's room for improvement and possibly implementing our own normalisation.

**Comment by budde377** [comment]
https://github.com/gql-dart/ferry/pull/359

**Comment by budde377** [comment]
Normalize `0.6.1` has been released which addresses these issues.

**Comment by vincenzopalazzo** [comment]
Do we need to release a new version of our package? I did not check our pub spec

**Comment by budde377** [comment]
The new version should be covered by our version range, so I expect not.
