### ISSUE TITLE
Exception: OperationException(linkException: ResponseFormatException(originalException: FormatException: Unexpected character (at character 1)

### ISSUE THREAD

**Issue by alexaung** [zino-hofmann/graphql-flutter#1181]
<!--  
**Describe the issue**
```
Exception: OperationException(linkException: ResponseFormatException(originalException: FormatException: Unexpected character (at character 1)
<!DOCTYPE html>
^
), graphqlErrors: [])
```

**To Reproduce (MUST BE PROVIDED)**

I found this issue recorded in firebase crashlytics. There are so many crash report but I can see this error in my devices but I can get the data immediately request again. It is very difficult to say that it is internet connection issue. 

**Expected behavior**
I should get data instead of error.

**device / execution context**
All of all devices

**Comment by vincenzopalazzo** [comment]
Please try again with more information!

**Comment by alexaung** [comment]
Oop! All my information are gone somehow. Ok I will post again.

**Comment by tyrone-horizonlabs** [comment]
did you got it working?
