### ISSUE TITLE
Union query doesn't return attributes

### ISSUE THREAD

**Issue by mwoszczyna** [zino-hofmann/graphql-flutter#1189]
Hi there, I run into a problem:

I'm trying to run a query including the following part of the query
```
asset {
            ... on AssetInterface {
              id
              name
              imageUrl
           }
}
```

The query as it self returns all expected values (attributes) apart of the `asset`

Not sure why the `asset` fragment in the response returns type only: 
`asset: {__typename: AssetFootballerNode}`

I was expecting to see some extra attributes as per query: 
`asset: {__typename: AssetFootballerNode, id: 'something, name: 'something', imageUrl: 'something' }`

When running same query in the standalone gql client it works perfectly fine. 

Is it a bug, am I missing something?

**Comment by budde377** [comment]
Are you using any code generators?

**Comment by budde377** [comment]
Please provide a reproducible example. 

* How does your client setup look? Have you setup `possibleTypes` correctly.
* How does your schema look like?
* Are you using any code-generators?

If you need help debugging, please head over to our discord and we'll sort your out.
