### ISSUE TITLE
Exceptions not being caught in try catch

### ISSUE THREAD

**Issue by joao-albach** [zino-hofmann/graphql-flutter#1201]
**Describe the issue**
When using the client whenever there is an erro in the request the exception is not caught, it does not matter if its in a `try catch` or i'm using `onError` it always crashes.

**To Reproduce (MUST BE PROVIDED)**

```
  GraphQLClient getClient(String baseUrl) {


    final HttpLink link = HttpLink(
      baseUrl,
    );

    GraphQLClient client = GraphQLClient(
      link: link,
      // The default store is the InMemoryStore, which does NOT persist to disk
      cache: GraphQLCache(),
    );

    return client;
  }
  
  Future<Thing> getThing() {
  try {
      final client = GqlClient().getClient(baseUrl);

      final result =
          await client.query(QueryOptions(document: gql(getThingQuery)));
} catch (e) {
      print(e.toString());
    }
  }
```

**Expected behavior**
I expect the error to be printed instead of the app crashing, instead it crashed with this exceptions:
```
OperationException(linkException: ServerException(originalException: null, parsedResponse: Response(data: null, errors: [GraphQLError ......
```

**device / execution context**
iOS simulator

**Comment by vincenzopalazzo** [comment]
Can you report a new issue also with the crash of `onError`??

I think with the actual API call you should check if there is an exception is `hasException` or something like that. and you can get the exception with `result.exception`

But your is a good point, maybe we could add a new method or introduce a way to support both supports both API

**Comment by joao-albach** [comment]
it is crashing before the i check for the result.hasException, but i just realized that it's an vscode debbug option... sorry

![image](https://user-images.githubusercontent.com/5909121/184931617-25b467cd-4ea5-4470-998d-eedb3026ca43.png)
