### ISSUE TITLE
Why does refetch function does not take variable ?

### ISSUE THREAD

**Issue by Arpit1496** [zino-hofmann/graphql-flutter#1202]
Currently when we use generated hooks to fetch query, we cannot pass variable to refetch function.
I want to refetch same query but with different variables.

**Comment by vincenzopalazzo** [comment]
A code example could be very useful here, maybe a comparison of what we have and what you would like to have.

**Comment by budde377** [comment]
Because refetching means fetching the same query again. If you want to fetch something with different variables you should store the variables in some state, update them, and they will update your query.

**Comment by Arpit1496** [comment]
So are you suggesting that changing the variable in useQuery will make it fetch again automatically ?

**Comment by budde377** [comment]
Yes, it should!
