### ISSUE TITLE
I had an issue: 'Property __typename on Query does not exist'

### ISSUE THREAD

**Issue by SalihCanBinboga** [zino-hofmann/graphql-flutter#1215]
**Describe the issue**
A clear and concise description of what the problem is.

**To Reproduce (MUST BE PROVIDED)**

When I run the below code snippet I have the below error:

`   final HttpLink httpLink = HttpLink(
      'https://dev-graphql-api.qoolomb.com/graphql',
    );

    final AuthLink authLink = AuthLink(
      getToken: () async =>
          'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBdXRoZW50aWNhdGlvbiIsInJvbGVzIjpbIlVTRVIiXSwiaXNzIjoicW9vbG9tYi5jb20iLCJpZCI6MTQsImFjY2Vzc1Rva2VuIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmxlSEFpT2pFMk5qRTJPVFkzT1RJc0luVnpaWEpmYm1GdFpTSTZJakUwSWl3aVlYVjBhRzl5YVhScFpYTWlPbHNpVWs5TVJWOVZVMFZTSWwwc0ltcDBhU0k2SWpCbU9XVTFaamc0TFRjeVpEZ3ROR1U0T0MwNFpHVTJMV1k0WmpNME56QXlNekEyT0NJc0ltTnNhV1Z1ZEY5cFpDSTZJbXh2WjJsdUlpd2ljMk52Y0dVaU9sc2liRzluYVc0aVhYMC5ORWF5aVFUOG13OEQ5Rk9PTklmUzh5QlZiYlZzSDVqakFwYnlLeEtSZ2NzIiwiZXhwIjoxNjYxNzI5MTkyLCJlbWFpbCI6InNhbGloY2FuYmluYm9nYTFAZ21haWwuY29tIn0.f88wau-13rDclECgQd5Wfzno0rJ4GW28Jo99gTWywzbHxG5zwaewckyj6xml7cqrgvsNM-oOCQWZ6udcGDqD4g',
    );

    final Link link = authLink.concat(httpLink);

    final GraphQLClient client = GraphQLClient(
      cache: GraphQLCache(),
      link: link,
    );

    const String readCategories = r'''
query GetCarCategories($parentId: Int!){
	getCarCategories(parentId: $parentId) {
		id
		title
	}
}
''';

    final QueryResult<Object?> resulttt = await client.query(
      QueryOptions(
        document: gql(readCategories),
        variables: const <String, dynamic>{
          'parentId': 101,
        },
      ),
    );

    if (resulttt.hasException) {
      print(resulttt.exception.toString());
      /*
      OperationException(linkException: null, graphqlErrors: [
      GraphQLError(message: Property __typename on Query does not exist, 
      locations: [ErrorLocation(line: 2, column: 3)], path: [], extensions: null)])
       */
    }`

**Expected behavior**
I want to expect clear response.

**device / execution context**
I have tried real device on ios. Remote server.

**Comment by budde377** [comment]
`gql` is adding the property `__typename` on every selectionset. It looks like your server doesn't support introspection on the `Query` type. Either enable introspection or use another implementation of `gql`. If you do not support the `__typename` introspection field in general, you can not expect caching to work properly.

**Comment by SalihCanBinboga** [comment]
@vincenzopalazzo @budde377 But I can add `__typename` parameter in my own query manager?w

**Comment by budde377** [comment]
Okay. I'm not sure what to tell you. The error message is from your server, it complains that you're trying to query `Query.__typename`. So you have two options:

* not fetch `__typename`
* fix your server

**Comment by vincenzopalazzo** [comment]
+1 for `fix your server`
