### ISSUE TITLE
Error with 'Graphql' after upgrading to Flutter 3.3.0.

### ISSUE THREAD

**Issue by inc16sec** [zino-hofmann/graphql-flutter#1220]
After upgrading to Flutter 3.3.0 and trying to run my app. Xcode threw an error.
`
../../../../documents/flutter/.pub-cache/hosted/pub.dartlang.org/graphql-5.1.2-beta.4/lib/src/exceptions/exceptions_next.dart:43:13: Error: Too few positional arguments: 2 required, 1 given.
  }) : super(originalException);
            ^
../../../../documents/flutter/.pub-cache/hosted/pub.dartlang.org/graphql-5.1.2-beta.4/lib/src/exceptions/exceptions_next.dart:69:13: Error: Too few positional arguments: 2 required, 1 given.
  }) : super(originalException);
            ^
../../../../documents/flutter/.pub-cache/hosted/pub.dartlang.org/graphql-5.1.2-beta.4/lib/src/exceptions/exceptions_next.dart:133:12: Error: Too few positional arguments: 2 required, 1 given.
  ) : super(originalException);
           ^
../../../../documents/flutter/.pub-cache/hosted/pub.dartlang.org/graphql-5.1.2-beta.4/lib/src/exceptions/exceptions_next.dart:17:14: Error: Too few positional arguments: 2 required, 1 given.
      : super(null);
             ^
../../../../documents/flutter/.pub-cache/hosted/pub.dartlang.org/graphql-5.1.2-beta.4/lib/src/exceptions/network.dart:11:13: Error: Too few positional arguments: 2 required, 1 given.
  }) : super(originalException);
`

Looks like it has something to do with the `Graphql` package.

**Comment by vincenzopalazzo** [comment]
Feel free to reopen if the solution did not work

**Comment by inc16sec** [comment]
> 

What solution?

**Comment by vincenzopalazzo** [comment]
this one https://github.com/zino-hofmann/graphql-flutter/issues/1213#issuecomment-1225331645

**Comment by inc16sec** [comment]
> this one [#1213 (comment)](https://github.com/zino-hofmann/graphql-flutter/issues/1213#issuecomment-1225331645)

I tried it and it didn't work for me. Still getting the same error.

`
../../../../documents/flutter/.pub-cache/hosted/pub.dartlang.org/graphql-5.1.2-beta.4/lib/src/exceptions/exceptions_next.dart:43:13: Error: Too few positional arguments: 2 required, 1 given.
  }) : super(originalException);
`

**Comment by knaeckeKami** [comment]
Are you maybe using dependency overrides to gql_link 0.5.0 or something similar?

**Comment by inc16sec** [comment]
> Are you maybe using dependency overrides to gql_link 0.5.0 , gql_http_link or something similar?

I'm overriding `gql`. My dependencies consist of: 

```yaml
gql: ^0.14.1-alpha+1660490324839
graphql: 5.1.2-beta.4
graphql_flutter: 5.1.1-beta.4
```

And I'm overriding:

```yaml
dependency_overrides:
  gql: ^0.13.0
```

The reason I'm overriding `gql` is because I have a dependency conflict with `graphql: 5.1.2-beta.4`.

`
Because graphql 5.1.2-beta.4 depends on gql ^0.13.0 and project_dev depends on gql ^0.14.1-alpha+1660490324839, graphql 5.1.2-beta.4 is forbidden.
So, because project_dev depends on graphql 5.1.2-beta.4, version solving failed.
pub get failed (1; So, because project_dev depends on graphql 5.1.2-beta.4, version solving failed.)
`

**Comment by knaeckeKami** [comment]
yes. there's a reason for this error message ;) `gql` 0.14 is a breaking change and not compatible with the latest version of `graphql`.
Try depending on gql ^0.13 and remove the dependency override.

**Comment by inc16sec** [comment]
> yes. there's a reason for this error message ;) `gql` 0.14 is a breaking change and not compatible with the latest version of `graphql`. Try depending on gql ^0.13 and remove the dependency override.

You're right. After removing the dependency override and downgrading `gql` to `^0.13` it worked just fine.

Thank you @knaeckeKami  for you help. It is much appreciated.
