### ISSUE TITLE
graphql cache 

### ISSUE THREAD

**Issue by isshort** [zino-hofmann/graphql-flutter#1221]
without reloading page graphql data is not updating flutter.
I am using graphql and http for api in my project.
graphql for only read operations 
http for write and update operations

firstly I am running a graphql query  example get  list of product 
Than I updating a product for example favorite the product 
When again I am request to my previous graphql query my product isFavorite didn't changed until I reloading(or restarting ) the project.

**Comment by vincenzopalazzo** [comment]
we need an example for this! 

You can use our endpoint https://api.chat.graphql-flutter.dev/graphql

**Comment by isshort** [comment]
### Thanks @vincenzopalazzo  for your quick response 

   My query is  
       
     client=GraphQLClient(
         cache: GraphQLCache(),
          link:  "MY LINK"),
 - for example firstly I am getting list of restaurant my query 
   
        final _restaurantList = await client.query(
       QueryOptions(
        document: gql(path),
         variables: params,
        ),
       );


     
 -  After getting my restaurantList I want add a restaurant to my favorite list. 
   This favorite operation I working with REST API 
   

           final _favorite = await _clientHttp.patch<Favorite>(  
             ApiConstant.instance.favoriteRestaurant,
          fromJson: Favorite.fromJson,
         body: {
          'rowId': restaurantId,
         },
        );
 


  - After favoriting my restaurant when  I recall my restaurant list graphql query 

         final _restaurantList = await client.query(
          QueryOptions(
           document: gql(path),
            variables: params,
          ),
         );
     
  - The favorite is not updated 
   
-  All queries here I am using generic query
      
      



         test('Favorite Restaurant equal to favorite list detail', () async {
          const restaurantId = 11;
       - /// In this query 11.restaurant = false 
          final _restaurant1 = await _client.betaQueryList(
           path: RestaurantQuery.instance.restaurantListByCategoryId,
           fromJson: Restaurant.fromJson,
           model: restaurantModel,
           params: {'id': 3, 'page': 0, 'count': 10},
         );
      
        - /// In this query 11.restaurant = true 
         final _favorite = await _clientHttp.patch<Favorite>(
           ApiConstant.instance.favoriteRestaurant,
          fromJson: Favorite.fromJson,
          body: {
            'rowId': restaurantId,
          },
        );
        
          -/// In this query 11.restaurant = false did'nt update  
        final _restaurant = await _client.betaQueryList(
          path: RestaurantQuery.instance.restaurantListByCategoryId,
          fromJson: Restaurant.fromJson,
          model: restaurantModel,
          params: {'id': 3, 'page': 0, 'count': 10},
             );

**Comment by isshort** [comment]
** This the screen shot **
![Screen Shot 2022-09-01 at 16 30 15](https://user-images.githubusercontent.com/37234355/187895627-3b40c832-6ce8-4c2f-a2cf-7e37155fb2b4.png)

**Comment by isshort** [comment]
**Thanks Mr @vincenzopalazzo  for your response me quickly  **
 I found my question at  [[beingadrian](https://github.com/beingadrian)](https://github.com/zino-hofmann/graphql-flutter/issues/353)  issue 
It was with fetchPolicy
