### ISSUE TITLE
Subscription- Bad State : stream has already been listened to.

### ISSUE THREAD

**Issue by Arpit1496** [zino-hofmann/graphql-flutter#1223]
Hey, I recently got this problem again.
But this time, 1st time the socket connects and works perfectly fine. But on navigating back and forth to the same widget throws this error. 

Are we supposed dispose something even when using hooks generated by codegen ? Am I missing something ?

_Originally posted by @Arpit1496 in https://github.com/zino-hofmann/graphql-flutter/issues/1191#issuecomment-1230804072_

**Comment by vincenzopalazzo** [comment]
>navigating back and forth to the same widget throws this error.

need a reproducible! You can use https://api.chat.graphql-flutter.dev/graphql

**Comment by vincenzopalazzo** [comment]
closing for lack of reproducible, feel free to reopen it if you find a good example
