### ISSUE TITLE
graphql-ws support is there in this library?

### ISSUE THREAD

**Issue by Faiyyaz** [zino-hofmann/graphql-flutter#1229]
According to the apollo documentation, ```subscriptions-transport-ws``` is going to deprecated in favour of ```graphql-ws``` and i tried using the ```WebSocketLink``` for the ```graphql-ws``` but the server is giving me error that i am trying to call my api from a client who is using ```subscriptions-transport-ws```.

Please can anybody help me with this.

Thanks

Here is the link for the documentation for the same thing:
```https://www.apollographql.com/docs/apollo-server/data/subscriptions/```

**Comment by vincenzopalazzo** [comment]
We are in beta stage https://github.com/zino-hofmann/graphql-flutter/blob/main/packages/graphql/CHANGELOG.md#new-feature

feedback are welcome!
