### ISSUE TITLE
Enum value 'index' will result in error

### ISSUE THREAD

**Issue by steebchen** [zino-hofmann/graphql-flutter#1233]
When using an enum with a value 'index':

```
enum Stuff {
  index
}
```

This error pops up on generation:

```
[SEVERE] json_serializable:json_serializable on lib/graphql/graphql_gen.graphql.dart:

Bad state: Too many elements
```

Every other value seems to work.

**Comment by budde377** [comment]
This seem like a problem with your serialiser code generator rather than the client library.
