### ISSUE TITLE
is 5.1.2-beta.4 really 5.1.1-beta.4?

### ISSUE THREAD

**Issue by ristiisa** [zino-hofmann/graphql-flutter#1239]
In 
https://github.com/zino-hofmann/graphql-flutter/blob/main/packages/graphql/CHANGELOG.md latest version is 5.1.2-beta.4 but in https://pub.dev/packages/graphql_flutter/versions#prerelease 5.1.1-beta.4 is listed.

Which is right?

**Comment by vincenzopalazzo** [comment]
Please note graphql and graphql_flutter are two different project!

**Comment by vincenzopalazzo** [comment]
https://pub.dev/packages/graphql
