### ISSUE TITLE
Support for @include and @skip directives

### ISSUE THREAD

**Issue by mlars84** [zino-hofmann/graphql-flutter#1246]
**Is your feature request related to a problem? Please describe.**
Attempting to use the @include or @skip directives result in a `PartialDataException`. This would be a great feature for re-using queries in multiple places where some fields may not be needed in all cases.

**Describe the solution you'd like**
I'd like the @include directive to work as one would expect: 
    - If false, the decorated field or fragment in an operation is not resolved by the GraphQL server 
and the @skip directive to work as one would expect: 
    - If true, the decorated field or fragment in an operation is not resolved by the GraphQL server.

**Describe alternatives you've considered**
An alternative might be to create separate queries for each use-case, but the defeats the goal of reusability. 

**Additional context**
Thanks for considering!

**Comment by budde377** [comment]
Good idea! This issue should be directed to the normalize library, which is throwing this error.

**Comment by mlars84** [comment]
Ps, these directives are defined and required by the core GraphQL specification, so their support in the library is essential!

**Comment by budde377** [comment]
They are supported in this library, you need to create an issue on normalize

**Comment by vincenzopalazzo** [comment]
Issue reported https://github.com/gql-dart/ferry/issues/468

**Comment by vincenzopalazzo** [comment]
Ok it required just to upgrade the normalize version https://github.com/gql-dart/ferry/issues/468#issuecomment-1371920877
