### ISSUE TITLE
Don't Understand to Get Error Message

### ISSUE THREAD

**Issue by rrifafauzikomara** [zino-hofmann/graphql-flutter#1249]
Hi, I have a question about how to get real error message.

I have print the error by default like below.
```dart
      print('Rifa 1: ${error}'); // from OperationException
      print('Rifa 2: ${error?.linkException}'); // from LinkException
```

And this is the result for above code.
```dart
flutter: Rifa 1: OperationException(linkException: ServerException(originalException: null, parsedResponse: Response(data: null, errors: [GraphQLError(message: Token has expired., locations: null, path: null, extensions: null)], context: Context({ResponseExtensions: Instance of 'ResponseExtensions'}), response {errors: [{errorType: UnauthorizedException, message: Token has expired.}]})), graphqlErrors: [])
flutter: Rifa 2: ServerException(originalException: null, parsedResponse: Response(data: null, errors: [GraphQLError(message: Token has expired., locations: null, path: null, extensions: null)], context: Context({ResponseExtensions: Instance of 'ResponseExtensions'}), response {errors: [{errorType: UnauthorizedException, message: Token has expired.}]}))
```

As you can see above, the error is nested. But the point of error is `Token has expired`.

My question is how to print the `Token has expired` message only?

And also how to get status code of every error? As you can see above no status code printed.

**Comment by vincenzopalazzo** [comment]
You should be able to unwrap the exception, but this looks tricky and a smell from an app developer's point of view.

I will work on it to improve this use case, thanks to report it

**Comment by vincenzopalazzo** [comment]
looks like it is not a graphql error, and also you can not expect to have the same result inside the playground, try with curl!

In addition, these kind of error are some things that we want to improve and throw a generic error, with the possibility to look inside each single one

**Comment by vincenzopalazzo** [comment]
closing this in favor of this https://github.com/zino-hofmann/graphql-flutter/issues/1270

We can just improve the error handling
