### ISSUE TITLE
Module 'connectivity_plus' not found - Xcode build

### ISSUE THREAD

**Issue by AristideVB** [zino-hofmann/graphql-flutter#1254]
**Describe the issue**
Module 'connectivity_plus' not found on Xcode Build _(M1 Mac)_

**To Reproduce**

1. **Create brand new flutter App project** 
2. Add `graphql_flutter: ^5.1.0` to pubspec.yaml & import in main.dart
3. Run `flutter clean && flutter pub get`
4. Build project from Xcode on an iOS device 

**Expected behavior**
Build runs without failing from both the terminal & Xcode

**device / execution context**
iOS - Flutter Channel stable, 3.3.7, on macOS 12.6 21G115 darwin-arm,

Tried solutions from with no success : 

https://github.com/fluttercommunity/plus_plugins/issues/337

**Comment by vincenzopalazzo** [comment]
Please use the last version beta graphql flutter I do not think that this is our problem, looks like more of a configuration problem.
