### ISSUE TITLE
There was an error causing connection lost: Bad state: Cannot add new events after calling close

### ISSUE THREAD

**Issue by GujjuFlutterGuy** [zino-hofmann/graphql-flutter#1276]
There was an error causing connection lost: Bad state: Cannot add new events after calling close

Version: **5.1.1-beta.4**

Flow:
- Screen chat_room: Going back to home screen and calling `connectOrReconnect`
- When home screen come it firing this error and cannot listen subscription's result.

**Comment by vincenzopalazzo** [comment]
you are more that 1 year old. 

Please update the package and if the error persists make a reproducible example
