### ISSUE TITLE
How to attach Context to a Query or Mutation Widget

### ISSUE THREAD

**Issue by TesfahunK** [zino-hofmann/graphql-flutter#1280]
I have recently ran into a situation where i have to attach custom header for some queries and mutations on my app, the docs indicate that this package support a Context for an operation but fails to give any example, is there any example that shows the use of a `Context` in Query/Mutation widget? if there is none can you please include that in the docs? 

Thanks

**Comment by wildsurfer** [comment]
@TesfahunK could you share your solution, please?
