### ISSUE TITLE
pub.dev: ERROR: Missing concrete implementation of 'getter WebSocketChannel.ready'.

### ISSUE THREAD

**Issue by larry-cariq** [zino-hofmann/graphql-flutter#1282]
**Describe the issue**
The static analysis on pub.dev is reporting this error:
ERROR: Missing concrete implementation of 'getter WebSocketChannel.ready'.

**To Reproduce (MUST BE PROVIDED)**
browse to: https://pub.dev/packages/graphql/score

**Expected behavior**
No static analysis errors.

### Other useful/optional fields
<img width="824" alt="Screen Shot 2023-01-11 at 3 45 12 PM" src="https://user-images.githubusercontent.com/112455234/211914162-a68f229b-0bb2-46f6-a4e3-c03860767bcb.png">

**Comment by fennelhans** [comment]
I have proposed a PR to fix this issue: https://github.com/zino-hofmann/graphql-flutter/pull/1281

**Comment by fennelhans** [comment]
This is preventing my team from merging ANY code to our repo. I hope the PR is merged quickly.

**Comment by larry-cariq** [comment]
Same for my team.

How did something break this?

**Comment by mlars84** [comment]
Same issue here. My CI/CD is crashing due to this on flutter stable.

**Comment by vincenzopalazzo** [comment]
why not override the web_socket_channel version? the fix looks trivial there

**Comment by fennelhans** [comment]
> why not override the web_socket_channel version? the fix looks trivial there

Because the proper fix is a one-liner?

**Comment by nicholasspencer** [comment]
Seeing the same error.

**Comment by ricardoamador** [comment]
Hitting this issue as well. Can we have someone review the proposed change by @fennelhans please? This is a blocker now for my team.
```
../../.pub-cache/hosted/pub.dev/graphql-5.1.2/lib/src/links/websocket_link/websocket_client.dart:577:7: Error: The non-abstract class 'GraphQLWebSocketChannel' is missing implementations for these members:
   - WebSocketChannel.ready
  Try to either
   - provide an implementation,
   - inherit an implementation from a superclass or mixin,
   - mark the class as abstract, or
   - provide a 'noSuchMethod' implementation.
 ```

**Comment by devapalanisamy** [comment]
It is fine on my machine. But it breaks on CI/CD.

**Comment by fennelhans** [comment]
> It is fine on my machine. But it breaks on CI/CD.

It'll break if you do a `flutter pub upgrade`

**Comment by wesbillman** [comment]
Following up on @vincenzopalazzo 's comment. You can add this to your pubspec to fix your codebase until the time here had time to update
```yaml
web_socket_channel: 2.2.0
```

**Comment by vincenzopalazzo** [comment]
Thanks for testing my idea @wesbillman I will release a hotfix of the graphql client that uses a fixed version of web_socket_channel and we introduce the new one in 5.2.0
