### ISSUE TITLE
Error The non-abstract class 'GraphQLWebSocketChannel' is missing implementations, After upgrading flutter to 3.7

### ISSUE THREAD

**Issue by ikhsansumaila** [zino-hofmann/graphql-flutter#1292]
Hello, i just upgrading the flutter to version 3.7, and when i'm starting to run this error shown on debug console

**Comment by noobmaster19** [comment]
Hey facing same issue, did u fix it?

**Comment by ikhsansumaila** [comment]
> Hey facing same issue, did u fix it?

hello, im actually just upgrading the package version to 5.1.2, then it solved

**Comment by paraslamsong** [comment]
In my case, adding web_socket_channel: 2.2.0 to pubspec file solved the issue
