### ISSUE TITLE
Generate new version with latest bumps from #1285

### ISSUE THREAD

**Issue by williamhjcho** [zino-hofmann/graphql-flutter#1303]
Hi 👋 

it's been a while since https://github.com/zino-hofmann/graphql-flutter/pull/1285 was merged on the main branch, but no releases (or at least dev releases) were generated.

We're currently using git URL + sha version pinning on our pubspec files to get the latest versions, but on some rare occasions (on our CI) the pub get fails when running in parallel (must be something how pub get command handles dependencies & cache)

But either way, would it be possible to generate a (preview) release?

**Comment by vincenzopalazzo** [comment]
Yeah I will generate one beta soon!
