### ISSUE TITLE
"... on " keyword is not working

### ISSUE THREAD

**Issue by Flaming19** [zino-hofmann/graphql-flutter#1330]
**Describe the issue**
"... on " not working but same query is working in postman.

**Expected behavior**
Should return same as postman

**device / execution context**
android

**Comment by vincenzopalazzo** [comment]
We need a reproducer

**Comment by Flaming19** [comment]
not working with 
QueryOptions(
        document: parseString(

But working fine with
QueryOptions(
        document:
        gql(

So closing this issue, sorry for inconvenience.
