### ISSUE TITLE
Getting warnings in mutation.graphql.dart, querys.graphql.dart, schema.graphql.dart, 

### ISSUE THREAD

**Issue by Subhangi3** [zino-hofmann/graphql-flutter#1333]
I have added graphQL to our Flutter project.  After adding query and mutation, run below command in terminal 

**flutter packages pub run build_runner build --delete-conflicting-outputs**

But getting below warnings in **mutation.graphql.dart**, **querys.graphql.dart**, **schema.graphql.dart** File - 

- The imported package 'gql' isn't a dependency of the importing package.
- The variable name 'first_name' isn't a lowerCamelCase identifier.
- The variable name 'l$first_name' isn't a lowerCamelCase identifier.
- Use the 'is!' operator rather than negating the value of the 'is' operator.
- The variable name 'l$$__typename' isn't a lowerCamelCase identifier.
- The member 'signup' overrides an inherited member but isn't annotated with '@override'.

/// build.yaml File
`# build.yaml

targets:
  $default:
    builders:
      graphql_codegen:
        options:
          namingSeparator: ""
          clients:
            - graphql
          generatedFileHeader: "/// GENERATED CODE - DO NOT MODIFY BY HAND\n
/// *****************************************************\n
///  FlutterGen\n
/// *****************************************************\n\n
// coverage:ignore-file\n
// ignore_for_file: type=lint\n
// ignore_for_file: directives_ordering,unnecessary_import,implicit_dynamic_list_literal,deprecated_member_use\n\n"`

**we don't have any other warnings in our project except graphQL warnings. How can we only remove grapphQL warnings from the project?**

**Comment by vincenzopalazzo** [comment]
mh we do not have a code generator. so looks like you post the problem in the wrong package
