### ISSUE TITLE
Upgrade http from 0.13.0 to 1.0.0

### ISSUE THREAD

**Issue by gabsn** [zino-hofmann/graphql-flutter#1348]
<img width="934" alt="image" src="https://github.com/zino-hofmann/graphql-flutter/assets/18901085/0e915738-3c2d-4128-9c19-3c4744650fdb">

**Comment by LuisReyes98** [comment]
This is a breaking change for migrating to flutter 3.10.5

**Comment by tsouza** [comment]
Can we release a `v5.2.0-beta.5` with this fix?

**Comment by krrskl** [comment]
Hello!

Any stable release with this fix?
