### ISSUE TITLE
Operation not permitted when init by initHiveForFlutter

### ISSUE THREAD

**Issue by kurt-liao** [zino-hofmann/graphql-flutter#1380]
I got an error when I init the app by function `initHiveForFlutter` with debug mode in the VSCode.

Here is the error message:
```
PathAccessException (PathAccessException: Cannot open file, path = '/Users/august/Documents/graphqlclientstore.hive' (OS Error: Operation not permitted, errno = 1))
```

I know the function `initHiveForFlutter` is to init Hive with the document folder, but why it requires the permission? I search a while and think it doesn't need that permission.

My code get stuck at the first line in main
```dart
Future<void> main(List<String> args) async {
  await initHiveForFlutter(); // Exception occurred
  ...
}
```

**Environment**
macOS
flutter: 3.10.6
graphql_flutter: 5.1.2

**Expected behavior**

Init Hive without exception and should not ask for permission.

**screenshots**

![Screen Shot 2023-09-18 at 10 44 39 PM](https://github.com/zino-hofmann/graphql-flutter/assets/32745146/de71b208-8807-4ff5-aefd-ffe3bbbdbad0)

**Comment by vincenzopalazzo** [comment]
>OS Error: Operation not permitted, errno = 1))

This is a an OS error, we can not do nothing (maybe)/ Have you try to see if you have enough permission?

**Comment by kurt-liao** [comment]
> Have you try to see if you have enough permission?

Thanks for the quick reply. Yes, I have try to give the Document folder permission, and it will work. However, I don't want to ask the permission to the user on my app if possible.

**Comment by vincenzopalazzo** [comment]
I guess this is related to the app, we can not do nothing from the graphql package I think

**Comment by kurt-liao** [comment]
> I guess this is related to the app, we can not do nothing from the graphql package I think

@vincenzopalazzo I see, thanks. As I know Hive is used for caching in graphql_flutter, can I skip the `initHiveForFlutter` method if I don't need a cache in my app?

**Comment by vincenzopalazzo** [comment]
Yeah you can disable the cache and use the in-memory one or just nothing, you can take a look at the readme inside the package that you are using.

I am closing this due that it is an problem that we can not solve from the library point of view
