### ISSUE TITLE
[feature] add an easy way to add headers

### ISSUE THREAD

**Issue by subzero911** [zino-hofmann/graphql-flutter#1382]
I would like to have an option to easily add custom headers to requests.
The syntax I want to see:
```dart
final response = await authGqlClient!.mutate_BindChildCard(
      Options_Mutation_BindChildCard(
        headers: {
            'X-Testing': '1',
            'X-Testing-Try-Mock': 'BankCardsRequest;BankTokensRequest;BankDetailsRequest;BankBalanceRequest'
          },
        variables: Variables_Mutation_BindChildCard(
          input: Input_BindChildCardInput(
            cardId: cardId,
            childId: childId,
            userId: GetIt.I<UserController>().user!.id,
          ),
        ),
      ),
    );
```

Currently the only way to add headers it to add it on graphql client init:
<img width="923" alt="image" src="https://github.com/zino-hofmann/graphql-flutter/assets/12999702/3dd3e0d2-e99a-4036-968e-e6429e863df3">
I can't change headers afterwards for individual requests.

**Comment by ming-chu** [comment]
@subzero911  Maybe consider using a custom HttpClient for it:

```dart
  final httpLink = HttpLink(
    baseUrl,
    httpClient: YourHttpClient(),
  );
```

```dart
class YourHttpClient extends http.BaseClient {
  final http.Client _client;

  YourHttpClient({http.Client? client}) : _client = client ?? http.Client();

  @override
  Future<http.StreamedResponse> send(http.BaseRequest request) async {
    request.headers.addAll({
      'X-Testing': '1',
      'X-Testing-Try-Mock': 'BankCardsRequest;',
    });
    return _client.send(request);
  }
}
```

Hope it helps.

**Comment by subzero911** [comment]
Thanks! But would be still nice to have a simple way, without having to create a custom client.

**Comment by subzero911** [comment]
Thanks, but it wouldn't help.
We still add a HttpClient on a HttpLink creation stage and can't change it afterwards. So it won't be much different from the problem described in a starting post (even more code).
I would like to see the easier way, without having to create a custom HttpClient just in order to add headers.

**Comment by ming-chu** [comment]
Just for a workaround ...
When you have a HttpClient with control then you can change it if you want to.
Some sudo code here for your reference:
```dart
  final yourHttpClient = YourHttpClient();
  yourHttpClient.setHeader(xxxx);

  final httpLink = HttpLink(
    baseUrl,
    httpClient: yourHttpClient,
  );

 //....
  yourHttpClient.setHeader(xxxx);
  // your query here ...

```

**Comment by ming-chu** [comment]
maybe consider using `Context` when query🤔

**Comment by subzero911** [comment]
Looks like a solution

**Comment by ming-chu** [comment]
> Looks like a solution

Please close the issue if you think it's already solved.
