### ISSUE TITLE
New release request to fix upstream bugs

### ISSUE THREAD

**Issue by zifeo** [zino-hofmann/graphql-flutter#1386]
**Is your feature request related to a problem? Please describe.**

https://github.com/fluttercommunity/plus_plugins/issues/2216 in a upstream dependency was solved with the release of a new major version of connectivity_plus

**Describe the solution you'd like**

Publish a new beta with connectivity_plus in version 5.0.0.

**Describe alternatives you've considered**

Dependency overrides works until then.

**Additional**
None

**Comment by vincenzopalazzo** [comment]
I will do tonight or tomorrow morning, thanks

**Comment by josephelliot-wk** [comment]
Any update on this release?

**Comment by vincenzopalazzo** [comment]
ops I forget I will do it now
