### ISSUE TITLE
Support latest version of http package

### ISSUE THREAD

**Issue by gd46** [zino-hofmann/graphql-flutter#1418]
Trying to install latest version of http throws a package dependency issue saying it requires

http ^0.13.0

And the latest version of http is 1.2.1.

https://pub.dev/packages/http/changelog

Should support moving to the latest version of http package.

**To Reproduce (MUST BE PROVIDED)**

1. When I use 
 graphql: 5.1.3
 graphql_flutter: 5.1.2
2. try to upgrade http package dependency to latest 1.2.1
3. I get a dependency issue saying graphql requires ^0.13.0.

**Expected behavior**
 I would like to be able to support the latest version of http package with the latest versions of graphql packages.

**device / execution context**
Issue is building iOS, or Android, I haven't tried Web

**Comment by vincenzopalazzo** [comment]
Are you able or do you like to open a PR for this?
