### ISSUE TITLE
Please add support for connectivity_plus 6.0.2

### ISSUE THREAD

**Issue by Avinash-dhiraj** [zino-hofmann/graphql-flutter#1423]
**Problem statement:** As app store introduced mandatory privacy manifest files for some of packages being used in the application. connectivity_plus 6.0.2 is one of them and current version of connectivity_plus 6.0.2 has added support for privacy manifest but graphql_flutter still using connectivity_plus 5.0.0 which leads into compatibility issue. App store is very specific about the deadline of these as well which is 1st of may.  
https://developer.apple.com/support/third-party-SDK-requirements/

Please update the connectivity_plus package to the latest

**Comment by Avinash-dhiraj** [comment]
I have created a PR with changes
https://github.com/zino-hofmann/graphql-flutter/pull/1424
Please check and do the needful.

**Comment by callmephil** [comment]
much needed ^

**Comment by SachinCodeMatrix** [comment]
Still crashes ios app

**Comment by AymanElarian** [comment]
any update about this ?

**Comment by vincenzopalazzo** [comment]
Please see `graphql_flutter-v5.2.0-beta.7`
