### ISSUE TITLE
bump connectivity_plus dependency

### ISSUE THREAD

**Issue by subzero911** [zino-hofmann/graphql-flutter#1467]
I added `vpn_connection_detector: ^1.0.9` to the project and received the following error:

<img width="984" alt="image" src="https://github.com/user-attachments/assets/ebe8715e-a0ab-4010-8c5c-fdd64724d384">

I temporarily solved it with:

```yaml
dependency_overrides:
  connectivity_plus: ^6.1.0
```

Please consider raising your `connectivity_plus` version.

**Comment by subzero911** [comment]
I bumped my `fresh_graphql` to ^0.6.1 and my `graphql` to ^5.2.0-beta.9, and it solved the issue

**Comment by vincenzopalazzo** [comment]
by Christmas I will release the 5.2, but probably this was not solving your issue tho
