### ISSUE TITLE
Please update the Dart SDK version.

### ISSUE THREAD

**Issue by hina06botify** [zino-hofmann/graphql-flutter#1469]

**Comment by hagen00** [comment]
A PR has just been merged that updates SDK as follows:
```
environment:
  sdk: '>=3.0.0 <4.0.0'
```

Previously it was `>=2.15.0 <4.0.0`

If you are happy with the change, please close this issue?

**Comment by vincenzopalazzo** [comment]
Use beta.10, thanks @hagen00
