### ISSUE TITLE
Can't connect to localhost in some setups

### ISSUE THREAD

**Issue by micimize** [zino-hofmann/graphql-flutter#212]
This is pulled out of #186 as more general "development configuration"/documentation issue. This thread is generally documenting and organizing network (or seemingly network) issues. Some goals:
* nailing down exact conditions we expect connections to work
* ensuring they work (i.e. #210)
* raising an intelligible error when there's something wrong (#177)

#### How to connect to localhost to different environs:
android simulator: Set host to `10.0.2.2`
android device: `adb reverse` should work
iOS device: serve from and connect to your IP address (or alternatively `mycomputername.local` on mac)
iOS simulator: should work with `localhost`

#### Troubleshooting tips:
The ["random ports" ](https://stackoverflow.com/questions/47372568/how-to-point-to-localhost8000-with-the-dart-http-package-in-flutter?rq=1) can happen as a result of network issues. A temporary workaround might be to use [`ngrok`](https://ngrok.com/)

**Comment by vincenzopalazzo** [comment]
This is related to the server that does not add the CORS header!

This is usually done by the proxy server or web server like nginix for this reason in the local host this error happens.

In order to solve this error, the server should include in the response the CORS header
