### ISSUE TITLE
Types generation

### ISSUE THREAD

**Issue by lucasavila00** [zino-hofmann/graphql-flutter#26]
I can make a generator for the types, but it would be nice to pass the parameters to the runtime.
I think Dart doesn't allow it, but how could we go towards that full typed approach?
I haven't written a single line of Dart but I liked Flutter a lot, but I'd need to use it with GraphQL. I can help with the GraphQL part but I would need help with Dart.

**Comment by HofmannZ** [comment]
@degroote22 Yes we are planning to create a fully typed library. Right now we mainly need it to handle caching more effectively, by actually passion response date into the appropriate GraphQL types. Feel free to try implementing a generator, we will jump in to help with Dart to make something great together.

**Comment by degroote22** [comment]
As soon as I have news I'll give a shout here.

**Comment by degroote22** [comment]
I got a prototype working.
It's very rough but it works with the example from this project.

I'm using a [fork of the generator](https://github.com/degroote22/graphql-code-generator) for now (peding issue that I haven't created) and a [custom template](https://github.com/degroote22/dart-template).

[See how it would be added to the example folder of this repository.](https://github.com/zino-app/graphql-flutter/compare/master...degroote22:master)

I'd appreciate feedback 👍

**Comment by HofmannZ** [comment]
Great work!

I really like how you generate the comments for the classes, so that you have some documentation while coding.

On the other side it feels a bit weird to have javascript running inside a dart project.

It would be possible to use [graphql_parser](https://github.com/angel-dart/graphql/tree/master/graphql_parser) to process the query strings.

**Comment by gedw99** [comment]
I am using that parser. It works well !

**Comment by degroote22** [comment]
The way types are being generated is with 2 things, the generator and the template.
The generator does more than just parsing the operations, it checks for errors in the operations agains the schema and pass to the template a flattened structure that's easier to use.
I'd rather work on a good template than reimplementing graphql-code-generator, at least for now.
The current generator has watch mode and the performance is okay, when used like this you don't even remember the fact that it is JS.

**Comment by gedw99** [comment]
There are many graphql parsers and generators in golang. Because it's golang which has built in code gen at its core it already supports many frontend languages. It can also do graphql to grpc and db gen. All from the graphql schema.

**Comment by degroote22** [comment]
@gedw99 Go is faster than JS but the friction would be there anyways.
IDK if it would be worth the trouble.

**Comment by micimize** [comment]
I've got serviceable type generation with [graphql-to-dart](https://github.com/micimize/graphql-to-dart) working, although it still has some limitations. For instance, it doesn't extract graphql strings form dart code, and I still feel like I might be generating non-idiomatic code.

Eventually doing code generation with dart faculties would be more convenient, build process wise, but I don't think it's a priority for anyone anytime soon.

**Comment by micimize** [comment]
I'm not sure if `graphql-flutter` itself should attempt to generate types, at least at first.
Rather, I think we should provide an api for a user to integrate their own generated types, and possibly a seperate type generation project.

**Comment by amadeu01** [comment]
@lucasavila00 that generator https://github.com/comigor/artemis seems really cool 
it might help as a base to create a generator for _graphql-flutter_

**Comment by HofmannZ** [comment]
@amadeu01 Nice suggestion!

@comigor Would you be interested in moving your type generator under the `graphql-flutter` project? I think it would be awesome for new developers to get type generation out of the box. What do you think?

**Comment by comigor** [comment]
Hey guys!

Yeah, I also think this project would benefit from types generation, and that's why I've started Artemis, actually. The goal of it is to have GraphQL type generation for any Dart project, not just Flutter-based projects (I'm already using it with Flutter for desktop and some CLI's).

It was on my roadmap to make a Flutter widget layer to it and, for this, `graphql_flutter` would be an awesome vessel; but I think the `graphql` package has some conflicts of how I'd like Artemis to work (be pure Dart, use Dart's `http.Client` instead of a custom non-plugabble approach, for instance, or having cache and auth layer decoupled).

Would it be possible to just reference Artemis on `graphql_flutter` for now? This way I could keep focusing on it, and it would even help guiding me to write more documentation and tests.

**Comment by micimize** [comment]
@comigor I don't see any issue with that - if I can manage to replace `graphql-to-dart` with `artemis` I might start incorporating some [typed widgets](https://github.com/micimize/graphql-to-dart/blob/master/example/lib/typed_query.dart) / helpers here.

There are some features we have implemented that I'd like to publish as standalone modules eventually, namely caching. So, if you go to add caching support, I'd rather put in the time to break that out, and work with you to get an appealing API design and the features you need.

`graphql` is pure Dart, btw

**Comment by comigor** [comment]
Yeah, I'd like to have cache (and even HTTP) decoupled from the code generation, but I had to create `ArtemisClient` abstraction to automatically get typed input/response from a query.

And what I meant of "pure Dart" is just using some default abstractions (like `http.Client` instead of `HttpLink` and things like that).

I didn't know about `graphql-to-dart`, but what I like most about Artemis is having it integrated with Flutter/Dart builder while generating code.

Ping me if you want some help on the migration! I'm actively working on Artemis right now (and adding documentation as we speak).

**Comment by smkhalsa** [comment]
Now that #429 has been merged, is there a plan to integrate https://github.com/comigor/artemis?

**Comment by micimize** [comment]
@smkhalsa in a sense - at the least, I'm probably going to start implementing a 3rd party code that does so, and if it gets to a mature state I'll PR it as another package.

**Comment by comigor** [comment]
Hey guys, how are you doing?

With the introduction of `Queries` (see [this example](https://github.com/comigor/artemis/blob/master/example/pokemon/lib/graphql/simple_query.dart#L39-L83)), the code generated from Artemis could already be used in conjunction with graphql-flutter: one could link this with a custom `QueryOptions`, for example, and that's it.

Are guys thinking in another kind of integration? I hope we can think in a first-class integration, but without losing the customization possibilities of Artemis.

**Comment by oexza** [comment]
> Hey guys, how are you doing?
> 
> With the introduction of `Queries` (see [this example](https://github.com/comigor/artemis/blob/master/example/pokemon/lib/graphql/simple_query.dart#L39-L83)), the code generated from Artemis could already be used in conjunction with graphql-flutter: one could link this with a custom `QueryOptions`, for example, and that's it.
> 
> Are guys thinking in another kind of integration? I hope we can think in a first-class integration, but without losing the customization possibilities of Artemis.

Can you make an example of this? I'm curious to see how this would work.

**Comment by vasilich6107** [comment]
@oexza 

Here is a fresh example from my today experiments. Works pretty fine.

```
              Query(
                options: QueryOptions(
                  documentNode: EmployeeQueryQuery(
                          variables: EmployeeQueryArguments(id: '123'))
                      .document,
                  variables: EmployeeQueryArguments(id: '123').toJson(),
                ),
                builder: (
                  QueryResult result, {
                  Future<QueryResult> Function() refetch,
                  FetchMore fetchMore,
                }) {
                  if (result.hasException) {
                    return Text(result.exception.toString());
                  }

                  if (result.loading) {
                    return const Center(
                      child: CircularProgressIndicator(),
                    );
                  }

                  final test = EmployeeQuery.fromJson(result.data);

                  debugPrint(test.employee.firstName);

                  return Container();
                },
              )
```

**Comment by michaellee8** [comment]
What is the status of this one? Are there any documentations yet?

**Comment by vasilich6107** [comment]
https://medium.com/@v.ditsyak/ultimate-toolchain-to-work-with-graphql-in-flutter-13aef79c6484

**Comment by michaellee8** [comment]
> https://medium.com/@v.ditsyak/ultimate-toolchain-to-work-with-graphql-in-flutter-13aef79c6484

Thank you, this one look nice. It will be great if this can be added to the README so that more people will be able to see that.

**Comment by vasilich6107** [comment]
@michaellee8 there is a PR for that...
@mainawycliffe @micimize please...

**Comment by vasilich6107** [comment]
@michaellee8 ready
https://github.com/zino-app/graphql-flutter#articles-and-videos

**Comment by budde377** [comment]
Both `artemis` and `graphql_codegen` provides code generation for `graphql_flutter` and `graphql`. I think relying on external libraries is a decent approach.
