### ISSUE TITLE
Korean Translation

### ISSUE THREAD

**Issue by serendipity1004** [zino-hofmann/graphql-flutter#455]
Startups in Korea are starting to pick up flutter and I think it would be great if this package could be translated into Korean and let it more known in Korea.

If you approve, I could work on translation and I am also intending to write a little Medium article on the usage. What do you guys think?

**Comment by mainawycliffe** [comment]
I think that would be amazing.

**Comment by serendipity1004** [comment]
I can work on this. Any directions on how you want to organize files, etc. Considering possibility of more languages being added in the future?

**Comment by mainawycliffe** [comment]
I am not sure, if you have any ideas, share them here and I will after some research we can compare notes. After that, you can get to work.

**Comment by serendipity1004** [comment]
@mainawycliffe https://github.com/tiimgreen/github-cheat-sheet this is one of the ways to do it. Simple and easy to implement I think. Just create same files with language extension e.g. README.ko.md and reference it in the top section.

**Comment by mainawycliffe** [comment]
@serendipity1004 I agree, we should do something like that.

**Comment by vincenzopalazzo** [comment]
Closing because it is tool old, happy to have this PR in BTW
