### ISSUE TITLE
[graphql_flutter] web support is not listed on pub

### ISSUE THREAD

**Issue by micimize** [zino-hofmann/graphql-flutter#644]
https://github.com/zino-app/graphql-flutter/issues/422#issuecomment-629700577:
On pub.dev `web` is not listed on platforms

![image](https://user-images.githubusercontent.com/3739536/82129405-3285b480-97cb-11ea-9fde-768b75c530fc.png)

unsure of what causes this

**Comment by smashedtoatoms** [comment]
Wait, does this work on web?  If it does that completely changes a decision I was about to make about whether to use flutter or not.  Can anyone confirm that this does work on web?

**Comment by smashedtoatoms** [comment]
Nevermind.  I found it.  This is awesome.  Thanks for all the hard work.  

https://github.com/zino-app/graphql-flutter/pull/590

**Comment by mdrideout** [comment]
Commenting that neither 3.x or 4.x display as being compatible with Flutter Web. I believe this is turning a lot of people away.
I had to hunt through the github issues to validate that users were actually able to use this on web.

As web is becoming pretty stable, I would like to ask that this is indicated on pub.dev and potentially add notes in the README if there are still stability issues with web.

**Comment by micimize** [comment]
[graphql v4](https://pub.dev/packages/graphql/versions/4.0.0-beta.3) displays web support – in fact the only `graphql_flutter` dependency that doesn't have it is [`path_provider`](https://pub.dev/packages/path_provider): https://github.com/flutter/flutter/issues/45296

**Comment by mdrideout** [comment]
@micimize I can't believe I missed that... could've sworn it was missing. Thanks!

**Comment by fogelfish** [comment]
Web support is still not listed on pub.

**Comment by micimize** [comment]
RIght – we depend on `path_provider` which still has no web equivalent. I believe we need the issue I linked above to be resolved, or for a 3rd party library which wraps our path_provider usage in conditional imports

**Comment by lukepighetti** [comment]
This package is also causing nhost packages to show as android / iOS only. Lots of people are skipping mobile only packages so I think this deserves another look.

**Comment by micimize** [comment]
@lukepighetti if you want to PR a fix for this go for it – maybe we can conditionally import it here? I'm not sure how it determines the badges really.
https://github.com/zino-app/graphql-flutter/blob/f552209ff270c057ebb710b0eca8366e8dd8660d/packages/graphql_flutter/lib/src/hive_init.dart#L5

I'm not actively working on this project much these days aside from still wanting to get the null safety release to stable

**Comment by lukepighetti** [comment]
> I'm not actively working on this project much these days aside from still wanting to get the null safety release to stable

Unsolicited advice, you might want to ask nhost if they are interested in taking over the package, or put up a deprecation notice.
