### ISSUE TITLE
Refetch stuck at loading when connection lost multiple times.

### ISSUE THREAD

**Issue by Bligoubloups** [zino-hofmann/graphql-flutter#807]
Hello !

If my device loses network connection and I try to refetch, nothing happens (except an exception that I handle)
When the connection is back, everything work normally.
But if this happens a second time, I get stuck loading.

I made a simple repo to reproduce this error. (Step to reproduce in the readme)
https://github.com/Bligoubloups/Flutter_Graphql_Refetch_unexpected_behaviour
This repo uses Graphql Flutter Widgets but I get same issue using ObservableQuery in my project.

Im using 4.0.0
It was working proprely on 3.1.0

Thank you for your help ! :D

**Comment by micimize** [comment]
@Bligoubloups I haven't really been able to reproduce on simulator – will have to try with a real device later.

One really strange thing is that even if I set `connectionTimeout` and `idleTimeout` on the inner client, and set the server to hang for 3 minutes, it _still_ doesn't time out and just waits until the response is received:
```dart
final hclient = HttpClient()
  ..connectionTimeout = Duration(seconds: 2)
  ..idleTimeout = Duration(seconds: 2);
final HttpLink httpLink = HttpLink(
  'http://localhost:6001/graphql',
  httpClient: http.IOClient(hclient),
);
```
```typescript
var lag: boolean = false

function later(delay: number, value: any) {
    return new Promise(function(resolve) {
        setTimeout(resolve, delay, value);
    });
}

const resolvers = {
  Query: {
    data() {
      const hello = "Hello " + new Date().toLocaleTimeString();
      if (lag) {
        lag = false
        return later(3 * 60_000, hello)
      }
      lag = true
      return later(1, hello)
    },
  },
};
```

**Comment by Bligoubloups** [comment]
Sometimes I have to delete the app to be able to reproduce the error.

The fact that it is waiting a response even if it should time out, is, I think, the main problem.

I'll try your code to see if it is related or not.

**Comment by Bligoubloups** [comment]
@vincenzopalazzo Could you take a look at this issue ? I still have this problem with 5.1.0.
Thanks !

**Comment by vincenzopalazzo** [comment]
>Could you take a look at this issue ? I still have this problem with 5.1.0.

This was not inserted inside the worklist, because the reproducible example was missing, so we don't know what is happening, because we can not see it.

>Sometimes I have to delete the app to be able to reproduce the error.

This is very messy for a bug report, but I put in the to-do list for the next months, if time or a better example will came we try to solve it for the release 5.2
