### ISSUE TITLE
cannot use context headers in GraphQL's subscription function.

### ISSUE THREAD

**Issue by kim-mini6** [zino-hofmann/graphql-flutter#815]
Is my code.

``` dart
final WebSocketLink websocketLink = WebSocketLink(
      'test',
      config: SocketClientConfig(
        initialPayload: {
          "headers": {},
        },
      ),
    );
```

I don't want to use headers in the code above.

Please look at the code below.

``` dart
SubscriptionOptions(
            operationName: 'messages',
            document: gql(r'''
              subscription messages($where: messages_bool_exp!) {
                messages(where: $where) {
                  ...messagesFragment
                }
              }
                ''' +
                fragments +
                '''
            '''),
            variables: {
              "where": {
                "id": {
                  "_eq": "test",
                },
              },
            },
            fetchPolicy: FetchPolicy.cacheAndNetwork,
            context: Context().withEntry(
              HttpLinkHeaders(
                headers: headers(idToken),
              ),
            ),
          );
```

Here I want to add a header to the context.

For general queries other than subscriptions, the context header works fine.

error message : cannot start as connection_init failed with : Missing Authorization header in JWT authentication mode.

**Comment by micimize** [comment]
This is a known issue – you can use [this workaround ](https://gist.github.com/micimize/04ee011b445d38ce34193a5225992504)in the meantime

**Comment by kim-mini6** [comment]
Thanks for the answer but it's not the workaround I want

**Comment by kateile** [comment]
@micimize the workaround works amazing. will `headers ` be added in the next WSLink?

**Comment by micimize** [comment]
@kateile after seeing the null safety v5 release to a stable version (along with its dependencies in the gql project), I do not plan on making any more feature or improvement contributions. Aside from the reasons I mentioned in #763, I have stopped using GraphQL in my own project and unfortunately it no longer makes sense for me to continue contributing here.

I haven't seen @HofmannZ or @eusdima around here in a long time so unless someone else steps in as active maintainer this project can be considered in low maintenance mode. Some people have expressed some interest in contributing in #762 but we'll see. Hopefully when I get around to the walkthrough vid it will help users PR fixes to their own problems.

**Comment by kateile** [comment]
@vincenzopalazzo can we solve this too in the coming updates?

**Comment by vincenzopalazzo** [comment]
Hi @kateile, these are some things that I can put in the queue, but do you test it with the last version of the package?

If yes, could you please propose a reproducible example?

**Comment by micimize** [comment]
@vincenzopalazzo this is more an API tweak for how to provide headers to the WebSocketLink. In essence, it would be adding a parameter to the default `connect` parameter, rather than requiring overriding it, so that a user could do the following:
```diff
SocketClientConfig(
  ...
- connect: (url, protocols) =>
-   IOWebSocketChannel.connect(url, protocols: protocols, headers: myCustomHeaders)
+ headers: myCustomHeaders
)
```

**Comment by vincenzopalazzo** [comment]
I implemented the feature suggested by @micimize (BTW thanks), in the following PR https://github.com/zino-hofmann/graphql-flutter/pull/1016 

I'm releasing the new beta version (beta.6), so we will be happy to receive feedback from the users

**Comment by kim-mini6** [comment]
Thank you very much. I will always support you!
