### ISSUE TITLE
Bad state: No element error

### ISSUE THREAD

**Issue by vasilich6107** [zino-hofmann/graphql-flutter#816]
**Describe the issue**
In case of server response code more than 300([here](https://github.com/gql-dart/gql/blob/master/links/gql_http_link/lib/src/link.dart#L123)) this line of code
https://github.com/zino-app/graphql-flutter/blob/beta/packages/graphql/lib/src/core/query_manager.dart#L202
throws 'Bad state: no element' error.

In my case I'm getting 401 Unauthorized error. But this error is being lost. On ui I'm getting only  'Bad state: no element' error

* Was there a **regression**?
No

**To Reproduce**
1. Go to make a request to any endpoint with response statusCode higher then 300
2. Check the query exception information

**Expected behavior**
It is expected that the error meaning and description is not being lost.

**device / execution context**
any device

**screenshots**
https://tppr.me/26LA4
https://tppr.me/P6Ph9

If you want to troubleshoot or discuss in real time, consider coming to the `support` channel in the [discord](https://discord.gg/tXTtBfC)

**Comment by micimize** [comment]
You're saying "Bad  state: no element" is within `result.exception`? Please copy `result.toString()` and show a sample of your `build` code

**Comment by vasilich6107** [comment]
I'll try to prepare a reproduction repo

**Comment by budde377** [comment]
This issue seems state. Closing.
