### ISSUE TITLE
Unhandled Exception: HiveError: This should not happen. Please open an issue on GitHub.

### ISSUE THREAD

**Issue by pokapow** [zino-hofmann/graphql-flutter#847]
Flutter 2.0.1 on Linux with graphql-flutter ^5.0.0-nullsafety.1

![image](https://user-images.githubusercontent.com/30467320/111903198-56480580-8a41-11eb-81f4-e14b2b27e658.png)

This happend systematicly since this morning, but I didn't change anything about this since weeks.

**Comment by micimize** [comment]
There could be a lot of reasons for this – try `flutter clean`, and take a look at https://github.com/hivedb/hive/issues/263. May be a usage issue on our end but hard to say

**Comment by budde377** [comment]
This issue seems to be stale. Closing.
