### ISSUE TITLE
LinkException when not using Mutation Widget

### ISSUE THREAD

**Issue by aseef17** [zino-hofmann/graphql-flutter#861]
**Describe the issue**
When not using the mutation widget and trying to get the error from the mutation, the following error is thrown

OperationException(linkException: UnknownException(NoSuchMethodError: The getter 'context' was called on null.
flutter: Receiver: null
flutter: Tried calling: context), graphqlErrors: [])

<img width="736" alt="Screenshot 2021-04-07 at 4 28 17 PM" src="https://user-images.githubusercontent.com/26878414/113855969-4577ed80-97be-11eb-8385-300c8a290e18.png">

When using the Mutation Widget, this error is not thrown

**Code**
<img width="571" alt="Screenshot 2021-04-07 at 4 22 23 PM" src="https://user-images.githubusercontent.com/26878414/113855546-c8e50f00-97bd-11eb-9916-faef61027d0b.png">

```
final QueryResult mutationResult = await graphQlClient.mutate(
        MutationOptions(
          document: gql(mutations.login),
          variables: {
            'email': email,
            'password': password,
          },
        ),
      );

      if (mutationResult.hasException) {
        debugPrint('Auth Login :- ${mutationResult.exception}');

      }
```

**Expected behavior**
Mutation Exception should show thee GraphQL errors as excepted

**Comment by micimize** [comment]
what version is this & what does your client declaration look like?

**Comment by aseef17** [comment]
> what version is this & what does your client declaration look like?

GraphQL version :- 4.0.1

The Client Declaration 

```
/// GraphQL functionality is initalised in [LocalGraphQLClient]
class LocalGraphQLClient {
  static BuildContext context;

  /// The [HttpLink] is used to intialise the base HTTP URl
  static final HttpLink httpLink = HttpLink(
    Endpoints.baseUrl,
  );

  /// The [AuthLink] is used to add the token to the Header of the request
  static final AuthLink authLink = AuthLink(
    getToken: () async => 'Bearer ${await UserRepository(context: context).getTokenRefreshed()}',
  );

  /// The [WebSocketLink] is used to work with GraphQL Subscriptions
  static final WebSocketLink websocketLink = WebSocketLink(
    Endpoints.wsBaseUrl,
    config: SocketClientConfig(
      inactivityTimeout: const Duration(hours: 2),
      initialPayload: () async => {
        "Authorization": 'Bearer ${await UserRepository().getToken()}',
      },
    ),
  );

  /// The [ErrorLink] is used to manage errors globally.
  /// Both the errors by thrown by GraohQL and by the Client are handled
  /// Client Error - [SocketExceptions], [MalformedExceptions] and more
  static final ErrorLink errorLink = ErrorLink(
    /// if `linkException` is `not null`, we show `noInternet` message
    onException: (
      Request request,
      Stream<Response> Function(Request) forward,
      LinkException exception,
    ) {
        ToastUtil.errorToast(message: Strings.noInternet);
      return null;
    },

    /// if `graphqlErrors` has some items, we display the message from the graphQL
    /// error message
    onGraphQLError: (
      Request request,
      Stream<Response> Function(Request) forward,
      Response response,
    ) {
      debugPrint('GraphQL Error :- ${response.errors[0].message}');

      debugPrint('$request');
      ToastUtil.errorToast(message: response.errors[0].message);

      return forward.call(request);
      // return null;
    },
  );

  /// We split the links based on a normal request and subscription [GraphQLClient]
  static final Link link = Link.split(
    (request) => request.operation.operationName != "getAccessToken",
    Link.split(
      (request) => request.isSubscription,
      websocketLink,
      authLink.concat(
        errorLink.concat(httpLink),
      ),
    ),
    httpLink,
  );

  /// [GraphQLClient] is initalised with the required parameters
  /// [initalizeClient] should be called at the root of your application
  static ValueNotifier<GraphQLClient> initailizeClient({
    UserRepository userRepository,
    BuildContext buildContext,
  }) {
    context = buildContext;
    final ValueNotifier<GraphQLClient> client = ValueNotifier(
      GraphQLClient(
        defaultPolicies: DefaultPolicies(
          query: Policies.safe(
            /// [FetchPolicy] is set to networkOnly to keep the application
            /// online only
            FetchPolicy.networkOnly,

            /// [ErrorPolicy] is set to none to ensure that no data is shown to
            /// the user when a error is thrown
            ErrorPolicy.none,

            CacheRereadPolicy.mergeOptimistic,
          ),
        ),

        /// We use the default [GraphQLCache] to support In-Memory cache
        cache: GraphQLCache(),
        link: link,
      ),
    );
    return client;
  }
}
```

**Comment by micimize** [comment]
>  ` static BuildContext context;`

> `await UserRepository(context: context)`

I'm guessing this is your issue. Idk what flutter does with `context` under the covers but maybe it gets disposed and then your `getTokenRefreshed` fails to find it's inherited widget or w/e. Try peppering some `prints` and exception handling in `getTokenRefreshed` to see if that's the issue

**Comment by aseef17** [comment]
> > ` static BuildContext context;`
> 
> > `await UserRepository(context: context)`
> 
> I'm guessing this is your issue. Idk what flutter does with `context` under the covers but maybe it gets disposed and then your `getTokenRefreshed` fails to find it's inherited widget or w/e. Try peppering some `prints` and exception handling in `getTokenRefreshed` to see if that's the issue

I tried adding debugPrint statements in the getTokenRefreshed method and no errors show up there. So that cannot be causing the problem for this

**Comment by micimize** [comment]
@aseef17 maybe try "pausing on all exceptions" in your IDE to see what exacty `.context` is being called on

**Comment by aseef17** [comment]
> @aseef17 maybe try "pausing on all exceptions" in your IDE to see what exacty `.context` is being called on

Sure. I'll try that.

But just discovered something that might be helpful for you to debug (Not sure though).

Tried to run my code with the **graphql_flutter: 4.0.0-beta.5** and it works fine. Doesn't throw any errors but with version **4.0.1**, the error is thrown.

<img width="736" alt="Screenshot 2021-04-07 at 4 28 17 PM" src="https://user-images.githubusercontent.com/26878414/113855969-4577ed80-97be-11eb-8385-300c8a290e18.png">

**Comment by milansurelia** [comment]
I am also getting this type of error after upgrading graphql_flutter.

Tried following versions of qraphql_flutter package:
- 5.0.1-beta.1
- 5.0.0
- 4.0.0-beta.5

Still getting the same error. Below is screenshot of error message.

![GraphQL_Link_Exception](https://user-images.githubusercontent.com/46532900/145933444-62946e0e-d1f7-4a0a-abb2-ae393196b46d.jpg)

**Comment by vincenzopalazzo** [comment]
@milansurelia 

By reading the issue, it is related to the client, but I'm happy to use my free time to debug your issue if you can produce a minimal example to reproduce the problem.

Thanks.

**Comment by budde377** [comment]
This issue looks stale. Closing for now.
