### ISSUE TITLE
request carshes when specifying operationName

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [zino-hofmann/graphql-flutter#863]
Hi,

I am using this version: graphql_flutter: ^4.0.0

I want to give name for my publich (nots authorized) operations names but when i am trying to execute query with name i get this error:

![image](https://user-images.githubusercontent.com/3918999/114307336-6fdbea80-9adf-11eb-9e5b-f9bc3f0d02db.png)

my create client code is this:

```
GraphQLClient createGraphqlClient({
  @required String uri,
  String subscriptionUri,
}) {
  Link link = HttpLink(uri);

  var authTokenService = GetIt.instance<AuthTokenService>();
  link = LocaleLink().concat(link);
  link = authTokenService.graphQLFreshLink.concat(link);

  if (subscriptionUri != null) {
    final WebSocketLink websocketLink = WebSocketLink(subscriptionUri,
        config: SocketClientConfig(
            autoReconnect: true,
            delayBetweenReconnectionAttempts: Duration(seconds: 2),
            initialPayload: () {
              return authTokenService.addAuthHeader(EnvVariables.currentHost);
            }));

    link = Link.split(
      (request) => request.isSubscription,
      websocketLink,
      link,
    );
  }

  link = errorLink.concat(link);

  final client = GraphQLClient(
    defaultPolicies: DefaultPolicies(query: Policies(fetch: FetchPolicy.noCache)),
    cache: GraphQLCache(store: HiveStore()),
    link: link,
  );

  return client;
}

```

I do not get any errors if i do not specify opeartionName

Any ideas why this is happening?

**Comment by vytautas-pranskunas-** [comment]
Any fix for this?

**Comment by budde377** [comment]
Can you please verify that this is still an issue with the latest version?

**Comment by budde377** [comment]
Sorry, I have no idea what that means. Can you please elaborate what you mean with operation specified in client but not in query?

**Comment by vytautas-pranskunas-** [comment]
in client: 
```
 _graphQLClient
        .query(QueryOptions(
          operationName: 'settingsGetAll',
          document: settingsGetAllQury,
          variables: {},
        ))
```

in query:
```
var settingsGetAllQury = gql(r'''
query settingsGetAll {
    settingsGetAll {
        ...
    }
}
''');
```

I mean you can have query without query name like this:
```
var settingsGetAllQury = gql(r'''
query {
    settingsGetAll {
        ...
    }
}
''');
```

or client call without operation name
```
 _graphQLClient
        .query(QueryOptions(
          document: settingsGetAllQury,
          variables: {},
        ))
```

any mismatch causes crashing

**Comment by vytautas-pranskunas-** [comment]
I have not tried all but looking at library code any mismatch should cause it because there is equality check something like this: ```operationName != otherOperationName``` (it is pseudo code not real one)
But i found it when i specified operation name on client but NOT in query

**Comment by budde377** [comment]
Alright, I'd generally expect specifying an operation name that isn't present in the document to fail. I'll close this issue, feel free to add documentation.
