### ISSUE TITLE
Caching behaviour changed with latest prerelease

### ISSUE THREAD

**Issue by reilem** [zino-hofmann/graphql-flutter#870]
**Describe the issue**

The caching behaves very differently now with version `5.0.0-nullsafety.2` and I was wondering if this was on purpose or a bug.

**Expected behavior**

Example which roughly sketches what I used to be able to do using `FetchPolicy.networkOnly`:
I used to be able to perform a query which resulted in:
```js
{
  foos: [
    { __typename: 'Foo', id: '1', amount: 5 },
  ]
}
```

And then later do a query which resulted in the following (basically all the changes "added" together are equal to the current "foo" state):
```js
{
  fooChanges: [
   {
     __typename: 'FooChange',
      id: '01',
      date: '2021-01-01T00:00:00',
      change:  {  __typename: 'Foo', id: '1', amount: 8 }
   },
   {
      __typename: 'FooChange', 
      id: '02', 
      date: '2021-01-01T01:00:00',
      change:  {  __typename: 'Foo', id: '1', amount: -5 }
   },
   {
      __typename: 'FooChange', 
      id: '03', 
      date: '2021-01-01T02:00:00',
      change:  {  __typename: 'Foo', id: '1', amount: 2 }
   }
  ]
}
```

**To Reproduce**

However, now when I use `FetchPolicy.networkOnly` using `5.0.0-nullsafety.2` then the second query results in this:

```js
{
  fooChanges: [
   {
     __typename: 'FooChange',
      id: '01',
      date: '2021-01-01T00:00:00',
      change:  {  __typename: 'Foo', id: '1', amount: 5 }
   },
   {
      __typename: 'FooChange', 
      id: '02', 
      date: '2021-01-01T01:00:00',
      change:  {  __typename: 'Foo', id: '1', amount: 5 }
   },
   {
      __typename: 'FooChange', 
      id: '03', 
      date: '2021-01-01T02:00:00',
      change:  {  __typename: 'Foo', id: '1', amount: 5 }
   }
  ]
}
```

All the "change" foo items are made equal to whatever the first query resulted in, which made the list in the UI completely useless since it just showed the same number. This seems very unintuitive to me? I spent around an hour debugging what was causing this issue until I realised it was graphQL caching issue. Because all my graphql requests via Apollo, our web app, and directly from the backend using whatever tool I could find returned the first result. And ONLY the mobile app using this library was returning something completely different.

I was already using the `networkOnly` policy so I would expect the network return to be respected no matter what. I was luckily able to fix my problem by using the `noCache` policy, but just letting you guys know in case this is some issue with latest prerelease you were unaware of.

**device / execution context**
N/A

**Comment by budde377** [comment]
I'd say this is working as expected; Network-only still saves to cache and I don't think your API makes a lot of sense. I understand that you want to view the changes and `Foo` objects at a given time, but the cache assumes that the `Foo` you're returning is the current one and consistent. Otherwise, how would we update the cache? 

The way to solve this, IMO, would be to add a custom cache key taking the timestamp of `Foo` into consideration.
