### ISSUE TITLE
Slow websocket reconnection

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [zino-hofmann/graphql-flutter#873]
I do not know why but reconnection to websocket is very slow. When it gets disconnected to any reason it says scheduling to connect in 2 seconds (or connecting to websocket) but stays like this for a minute or more.

![image](https://user-images.githubusercontent.com/3918999/115151571-bac0a980-a06d-11eb-8087-af3beeceac72.png)

In later versions reconnection was lightning fast.

I am using graphql_flutter: ^4.0.0

**Comment by vincenzopalazzo** [comment]
This should fix it https://github.com/zino-hofmann/graphql-flutter/issues/873
