### ISSUE TITLE
Can't add custom headers to WebSocketLink

### ISSUE THREAD

**Issue by danielk444** [zino-hofmann/graphql-flutter#876]
**Describe the issue**
HI, I'm using `WebSocketLink` for subscriptions. I would like to authenticate with my server by adding a token in a request header. I've tried using `AuthLink` like so:

```
_authLink = AuthLink(
      getToken: () async => 'Bearer $token',
      headerKey: 'Authorization'
    );
_link = _authLink.concat(_wssLink);
```

This has no effect and is not adding any header to a request. I've also tried to add `initialPayload`

```
SocketClientConfig(autoReconnect: true,
          initialPayload: () => {
            'headers': {'Authorization': 'Bearer $token'},
          }
      )
```

also nothing. Is there a way to add auth / custom headers to a `WebSocketLink`? I'm using version 4.0.1 of the graphql_flutter, thanks!!!

**Comment by vytautas-pranskunas-** [comment]
Watching

**Comment by vytautas-pranskunas-** [comment]
On prev versions initailPayload worked for me.

**Comment by kateile** [comment]
This solution [here](https://gist.github.com/micimize/04ee011b445d38ce34193a5225992504) worked really well in v4. But you can't use it in v5. So if you would rather use v4 that will solve your problem

**Comment by vytautas-pranskunas-** [comment]
Auth link works for me actually and I am adding bearer token there

**Comment by kateile** [comment]
@vytautas-pranskunas- can you share  sample code?

**Comment by vytautas-pranskunas-** [comment]
```
if (subscriptionUri != null) {
    final WebSocketLink websocketLink = WebSocketLink(subscriptionUri,
        config: SocketClientConfig(
            autoReconnect: true,
            delayBetweenReconnectionAttempts: Duration(seconds: 2),
            initialPayload: () {
              return authTokenService.addAuthHeader(EnvVariables.currentHost);
            }));

    link = Link.split(
      (request) => request.isSubscription,
      websocketLink,
      link,
    );
  }
```


```
  addAuthHeader(String? url, {Map<String, String>? headers}) {
    if (headers == null || url == null) {
      headers = new Map<String, String>();
    }

    if (_inMemoryTokenStorage._token == null || url!.indexOf(EnvVariables.currentHost) == -1) {
      return headers;
    }

    var token = hasToken ? 'bearer ' + _inMemoryTokenStorage._token!.accessToken : '';

    headers.putIfAbsent(HttpHeaders.authorizationHeader, () => token);

    return headers;
  }
```

**Comment by Fintasys** [comment]
I've tried the code above with version `5.0.0-nullsafety.5` and it didn't work for me 😢  Which version did you tried it with?

**Comment by kateile** [comment]
[here is really solution](https://github.com/zino-app/graphql-flutter/issues/902#issuecomment-847869946)
Happy coding

**Comment by cthurston** [comment]
Worth noting that the experimental method of adding headers to subscription connections does not work for Web. Maybe this bug is the best place to track that feature as well.

**Comment by supermar1010** [comment]
Just to report back, I had the same problem while adding my headers via the authLink or the SocketClientConfig.headers. What worked was using initialPayload:

```dart
    SocketClientConfig(
          initialPayload: () => {
                'headers': {'x-hasura-admin-secret': APISettings.apiKey},
              }));
```

**Comment by vincenzopalazzo** [comment]
@supermar1010 The API of the SocketClientConfig now accepts the header map, you don't need to pass this inside the init payload.

If this doesn't solve your problem, please open a new issue with more details.
