### ISSUE TITLE
Desktop support

### ISSUE THREAD

**Issue by lukepighetti** [zino-hofmann/graphql-flutter#879]
nhost is one of the only cloud providers with a pure dart SDK but their graphql package is constrained to Android/iOS because of graphql-flutter.

Unless there is a compelling reason for this package to be mobile only, it would benefit many if it were all-platform.

**Comment by shyndman** [comment]
Hey @lukepighetti,

I've been using it on macOS without issue, and I'm aware of others using Windows. What are you encountering?

**Comment by budde377** [comment]
This issue seems to be stale. Closing for now.
