### ISSUE TITLE
Adding hive gives an error

### ISSUE THREAD

**Issue by iamchathu** [zino-hofmann/graphql-flutter#880]
**Describe the issue**
As the documentation I have tried to add Hive to persist the cache. But after adding the dependancies as in hive documentation pub get fails with version mismatch.

**To Reproduce**
```yaml
...
  graphql: ^4.0.1
  hive: ^2.0.4
  hive_flutter: ^1.0.0
...
```

**Expected behavior**
Install the packages without issues.

### Other useful/optional fields

<details>
  <summary>Stacktrace:</summary>

```dart
Running "flutter pub get" in flutter_app...                     

Because flutter_app depends on graphql ^4.0.1 which depends on hive ^1.3.0, hive ^1.3.0 is required.
So, because flutter_app depends on hive ^2.0.4, version solving failed.
pub get failed (1; So, because flutter_app depends on hive ^2.0.4, version solving failed.)

```

</details>

**Comment by spiralni** [comment]
The same here. Any walkaround?

**Comment by mopilo** [comment]
any solution?

**Comment by sebalaursen** [comment]
You don't have to add `hive` as a separate dependency, it is included in `graphql-flutter` package itself. So, just don't add `hive` in your `pubspec.yaml`.

The issue you are getting is that  `graphql-flutter` already has `hive` as its dependency but it's using version `^1.3.0` and you are adding `hive ^2.0.4` manually thus the conflict with `flutter pub get`.

**Comment by iamchathu** [comment]
@sebalaursen What if I need to use `hive` for the project and I require latest version?

**Comment by sebalaursen** [comment]
@iamchathu You could try using [dependency overrides](https://dart.dev/tools/pub/dependencies#dependency-overrides) and just override `hive` to the version that you need. But it could cause `graphql` to break if it's using deprecated methods if that's the case then the only option would be to fork and update it yourself.

**Comment by budde377** [comment]
Hive has been updated in the latest release!
