### ISSUE TITLE
WebSocketLink.connectOrReconnect disposes the existing client, losing all subscriptions upon reconnect

### ISSUE THREAD

**Issue by shyndman** [zino-hofmann/graphql-flutter#892]
**Describe the issue**
I work on the [Nhost Dart API](https://github.com/nhost/nhost-dart), which uses JWT token refresh to re-authenticate periodically on a timer. This operation requires reconnecting any open web sockets, because we need to supply a new auth token in the socket's initial payload.

I'd been using `WebSocketLink.connectOrReconnect` to accomplish this, but we started receiving reports that subscriptions were mysteriously dying off. (https://github.com/nhost/nhost-dart/issues/9)

I dug in a bit, and found that `WebSocketLink.connectOrReconnect` disposes the previous socket client (the one with subscription knowledge), and starts using a new one (that doesn't know anything).

I propose that instead of recreating the socket client, we reuse it. The client's reconnection logic appears to be perfectly suited to doing this without much change, as it already re-establishes subscriptions on reconnect.

Are you open to a PR?

**Comment by vytautas-pranskunas-** [comment]
This repo has no active maintainer anymore. So PRs are welcome. Just drop a message to https://github.com/zino-app/graphql-flutter/issues/894 miscimize on how to merge it.

**Comment by vytautas-pranskunas-** [comment]
P. S. I have a problem that websocket closed after long idle with app in the background I receive 103 error. After resuming subscriptions not working untill app is restart. Do you think using WebSocketLink.connectOrReconnect in resume life cycle might fix this issue?

**Comment by vytautas-pranskunas-** [comment]
@shyndman I see you are contributor. Can you push fix for it?
