### ISSUE TITLE
📣 no active maintainer  📣

### ISSUE THREAD

**Issue by micimize** [zino-hofmann/graphql-flutter#894]
[5.0.0-nullsafety.5](https://pub.dev/packages/graphql/versions/5.0.0-nullsafety.5) is now published, and is the same as [5.0.0-beta.1](https://pub.dev/packages/graphql/versions/5.0.0-beta.1), but should be preferred as the dependency as I believe prereleases are alphanumerically prioritized.

After seeing v5 through to the stable channel, this is going to be the last major contribution I make to `graphql`/`graphql_flutter`, and I don't intend to make any changes/fixes unrelated specifically to the null safety work.

I hope I'm leaving a solid enough foundation for the package (and ecosystem) to continue to thrive/develop, but it no longer makes sense for me to work on, personally. If someone ends up doing serious development work and has a question for me, feel free to @ me on the discord.

**Comment by vytautas-pranskunas-** [comment]
This lib is critical for many teams. I believe it would be best if you contact flutter team and they take this lib under control because they have many plugins under development already.

**Comment by micimize** [comment]
@vytautas-pranskunas- I think apollo would be a better fit for a corporate sponsor/adopter, given that it is so similar to their other clients, but either way I personally have no plans of advocating for such adoption.

**Comment by vytautas-pranskunas-** [comment]
@micimize but you can not leave it like this leaving many projects with no support. I mean you can but this is not very nice attitude. I understand that you have no time but at least you could write to both - apollo and flutter team about your plans so we have at least some chance that it will be picked up. Why you? Because you know this prioject the best.

**Comment by micimize** [comment]
@vytautas-pranskunas- I started contributing to this library because it was important for my project and was missing features I needed. If it is important to your project, you can do the same. In my opinion, seeing this project through two major versions, one of which was after I had any personal stake in the project, was going above and beyond as a maintainer.

Regardless, what I or other maintainers do and don't owe their projects dependents is not up for debate, and to reflect that I'm locking this. As I've raised to you before, I suggest not treating the hard work of maintainers with such entitlement in the future.

**Comment by jhomlala** [comment]
> @micimize but you can not leave it like this leaving many projects with no support. I mean you can but this is not very nice attitude. I understand that you have no time but at least you could write to both - apollo and flutter team about your plans so we have at least some chance that it will be picked up. Why you? Because you know this prioject the best.

Regarding this rude comment - this project is open source which is same as Flutter. Not everyone has time for maintaining large projects. Anyway @micimize did good job announcing that he wanted to drop off from maintaining this project. I don't think so Flutter team will pick up this project. There's same problem with Dio library which wasn't updated for few months.

Please think twice before posting such as offensive comment for open source maintainer. @micimize has done great job creating this library and providing foundations for graph ql client. You can always use your spare time for creating PR for this library instead of forcing further support in @micimize.

**Comment by budde377** [comment]
Thank you work on this @micimize. I'm the maintainer for https://github.com/heftapp/graphql_codegen and could consider taking a more active part in this project, possibly consolidating the projects.

**Comment by vincenzopalazzo** [comment]
I'm also interested to work as a maintainer in this library to continue to maintain it, are you are searching maintainers @micimize?

Maybe I and @budde377 can be good candidates?

**Comment by jonorozcoc** [comment]
@micimize What about Flutter Community? 

btw, awesome work you've made until now ❤️

**Comment by vincenzopalazzo** [comment]
Hi @jonorozcoc,

Me and @budde377 are the new maintainer of the library, we will start to organize the work, and maybe move this to a more general organization.

Give use the time to jump inside. Thanks :)

**Comment by jonorozcoc** [comment]
@vincenzopalazzo @budde377 It's good to know the project we'll be alive. Let me know if I can help with something

**Comment by vincenzopalazzo** [comment]
If @micimize allow me, I would like to close this issue because the work that he made in this time will continue to survive 🗡️ 

Thank you!

**Comment by jonbhanson** [comment]
@vincenzopalazzo and @budde377 thanks for working on this project.  You can get paid for working on this project by applying for a grant from [GraphQL Community Grant Program](https://grant-application.graphql.org/).  Let me know if you need any help!

**Comment by jonbhanson** [comment]
And @micimize of course thank you for all the effort that you have already put into this package. 🤩  As a fellow package maintainer, I understand the commitment.

**Comment by micimize** [comment]
Thanks @jonbhanson! As Vincenzo has noticed we also have some change in https://opencollective.com/graphql-flutter

![mrs obama, it's been an honor](https://user-images.githubusercontent.com/8343799/147496937-f84ca1c4-cafc-497a-b9fd-c8a94002678a.png)
