### ISSUE TITLE
GraphQLError does not have "raw" attribute anymore

### ISSUE THREAD

**Issue by caiotl** [zino-hofmann/graphql-flutter#903]
I'm migrating graphql_flutter from 3.1.0 to 5.0.0-nullsafety.2 and I have a problem.
GraphQLError, from gql_exec package does not have a raw attribute anymore. I used to get the "errorType" and "code" from the raw attribute to throw custom exceptions based on this code and type, but now I can't get the raw error anymore.
I'm new to GraphQL and I saw recently an example where this information was in extensions, but I don't know if this is correct. It could be a solution, but I think the backend team would have to refactor a considerable number of code lines. If I could solve it myself, it would be better.
What can I do?

I opened this issue on gql GitHub, but they said this issue is related to graphql_flutter.
Here is my code, where I used to get this info from "raw":

```dart
extension QueryResultExtension on QueryResult {
  void parseException() {
    if (exception.clientException is NetworkException) {
      throw NoConnectionException();
    } else if (exception.graphqlErrors != null) {
      if (exception.graphqlErrors.first.raw['errorType'] ==
          'UnauthorizedException') {
        throw AuthenticationRequiredException();
      }
      throw GraphQLAPIException.fromJson(
          exception.graphqlErrors.first.raw['errorInfo']);
    }
    throw exception;
  }
}

**Comment by Fintasys** [comment]
I'm using following, might help you. `raw` seems to be not there anymore.
```
if (exception.graphqlErrors.first.extensions!['code'] == 'constraint-violation') {
        throw Exception('Entry already exists');
}
```
`extensions` seems to have only `path` and `code` as attributes.

**Comment by caiotl** [comment]
Seems to be a good solution, but currently the backend of my project returns null on `extensions`.
I talked to them and they said that `extensions` are only allowed by the ApolloServer. Apparently they don't use this ApolloServer.
We are doing a workaround adding the `code` and `name` to the `message`, so I can make a function to parse this information.
Seems a little weird but I think it will work.

**Comment by caiotl** [comment]
> I'm using following, might help you. `raw` seems to be not there anymore.
> 
> ```
> if (exception.graphqlErrors.first.extensions!['code'] == 'constraint-violation') {
>         throw Exception('Entry already exists');
> }
> ```
> 
> `extensions` seems to have only `path` and `code` as attributes.

Seems to be a good solution, but currently the backend of my project returns null on extensions.
I talked to them and they said that extensions are only allowed by the ApolloServer. Apparently they don't use this ApolloServer.
We are doing a workaround adding the code and name to the message, so I can make a function to parse this information.
Seems a little weird but I think it will work.

**Comment by Fintasys** [comment]
Ah I see ! I'm using Hasura as backend that's why it differs. TIL 🙇

**Comment by vincenzopalazzo** [comment]
Looks like no reproducible, so feel free to open the issue again if there is more clear way to debug it
