### ISSUE TITLE
AuthLink doesn't work with gql_dio_link

### ISSUE THREAD

**Issue by iamchathu** [zino-hofmann/graphql-flutter#911]
**Describe the issue**
Since we need to intercept errors and lock feature we have migrated from `http_link `to `gql_dio_link` and replaced httpLink in link chain with `dioLink`. But I'm getting authentication failed error since headers doesn't get set from `auth-link`

**To Reproduce**
1. Start from basic setup with AuthLink.
2. Install `gql_dio_link` dependancy.
3. Replace httpLink with dioLink
4. See the error

**Expected behavior**
Authtentication header should be set to dio link or should mention only works with httpLink.

**device / execution context**
Android

```
  graphql: ^4.0.1
  dio: ^4.0.0
  gql_dio_link: ^0.1.0
```

```
environment:
  sdk: ">=2.7.0 <3.0.0"
```

**Comment by budde377** [comment]
We're not the maintainers of `gql_dio_link`, I'd submit a request with them instead.

**Comment by mo-ah-dawood** [comment]
The problem is that `ggl_dio_link` use `HttpLinkHeaders` deferent from the one used by `ggl_http_link` 
and this package use the one in `ggl_http_link` so to solve this is to implement `AuthLink` by your self

**Comment by mo-ah-dawood** [comment]
```dart
import 'package:gql_dio_link/gql_dio_link.dart'; //important

class DioAuthLink extends Link {
  DioAuthLink();

  @override
  Stream<Response> request(
    Request request, [
    NextLink? forward,
  ]) async* {
    /// get your token
    final token = await getToken();
    var req = request.updateContextEntry<HttpLinkHeaders>(
      (headers) => HttpLinkHeaders(
        headers: <String, String>{
          ...headers?.headers ?? <String, String>{},
          if (token != null) "Authorization": token,
        },
      ),
    );

    yield* forward!(req);
  }
}
```
