### ISSUE TITLE
Error adding wrong typename in mutations

### ISSUE THREAD

**Issue by matias22x** [zino-hofmann/graphql-flutter#917]
Hello!
I have a problem using flutter graphql, when i post a mutation with the library, this send a typename in the query, I get an error because this create the mutation as

`mutation insertPlace($data: any) { __typename places(insert: $data) {...}}`

when I need that the mutation create as

`mutation insertPlace($data: any) {places(insert: $data) {...}}`

some solution to this?

I see that graphqlCAche sets a property addTypename with false but when i set this in my code, i receive an error "the named parameter 'addTypeName' isn't defined"

**Comment by tvc12** [comment]
same problem

> Hello!
> I have a problem using flutter graphql, when i post a mutation with the library, this send a typename in the query, I get an error because this create the mutation as
> 
> `mutation insertPlace($data: any) { __typename places(insert: $data) {...}}`
> 
> when I need that the mutation create as
> 
> `mutation insertPlace($data: any) {places(insert: $data) {...}}`
> 
> some solution to this?
> 
> I see that graphqlCAche sets a property addTypename with false but when i set this in my code, i receive an error "the named parameter 'addTypeName' isn't defined"

**Comment by budde377** [comment]
Can you provide a reproducible example? `graphql_flutter`/`graphql` doesn't add `__typename` but `gql` might. Feel free to re-open, if this is still an issue.
