### ISSUE TITLE
graphql client: How to pass authorization header in mutation and query request

### ISSUE THREAD

**Issue by coyksdev** [zino-hofmann/graphql-flutter#921]
Is there a way to pass the authorization header in mutation and query request, or a way to override httpLink default headers when calling the graphql client. 

For now what I did is I created a function that will build the client.

```dart
getGraphQLClient([String? accessToken]) {
  final httpLink = HttpLink(
    ConfigReader.getAppGraphqlEndpoint(),
    defaultHeaders: {'Authorization': 'Bearer $accessToken'},
  );

  return GraphQLClient(cache: GraphQLCache(), link: httpLink);
}
```

In my repository I called it every time when I am making a request.

```dart
Future<dynamic> currentUser(String accessToken) async {
    final client = getGraphQLClient(accessToken);

    final options = QueryOptions(
      document: gql(r'''
        query {
          currentUser
        }
      '''),
    );

    final QueryResult result = await client.query(options);

    if (result.hasException) {
      throw Failure(result.exception?.graphqlErrors.first.message);
    }

    return result.data!['currentUser'];
  }
```

**Comment by vasilich6107** [comment]
@campanagerald take a look at this link
https://github.com/felangel/fresh/tree/master/packages/fresh_graphql

**Comment by budde377** [comment]
Rebuilding the client is the way.

**Comment by donebeforesunset** [comment]
@budde377
If we rebuild the client every time, won't we lost our cache?

**Comment by budde377** [comment]
That depend on what cache you use and how you provide it. The cache is an argument to the client so you can just persist it if you'd like.
