### ISSUE TITLE
graphqlErrors: [GraphQLError(message: Null value resolved for non-null field `__typename`]

### ISSUE THREAD

**Issue by Flaming19** [zino-hofmann/graphql-flutter#926]
How can we resolved these errors?

Below is my queryresult:

QueryResult result = await _client.query(
      QueryOptions(
        document: gql(query),
      ),
    );

Client to query is : 
Future<GraphQLClient> clientToQuery() async{
    return GraphQLClient(
      cache: GraphQLCache(store: HiveStore()),
      link: httpLink,
    );
static HttpLink httpLink = HttpLink(
    getUrl(),
  );
  }

**Comment by KammererTob** [comment]
How does your query look like? Seems like you are not requesting `__typename` or your server does not return a value for it.

**Comment by micimize** [comment]
`gql` automatically adds `__typename` for every object. This is part of the graphql standard, but if your server cannot handle it, you can make a custom `gql`: https://github.com/zino-app/graphql-flutter/issues/814#issuecomment-782293733

**Comment by Flaming19** [comment]
@micimize    thanks.
#814   comment is non understandable, could you please letme know if you have and full example of it.

**Comment by micimize** [comment]
that is a full example of a custom `gql`. If you don't want automatic `__typenames` at all you can just use `parseString` from `gql:gql.dart` as used in the `gql` implementation I linked to

**Comment by AneesRazaRaise** [comment]
I'm facing the same issue. Although i'm using #814 solution and it works perfectly fine on mutation but on query it return nothing.

**Comment by micimize** [comment]
@AneesRazaRaise try using `parseString` instead of `gql`

**Comment by AneesRazaRaise** [comment]
Not working.!

**Comment by AneesRazaRaise** [comment]
Here is the interesting part. when i remove the cache dependence by using 
 fetchPolicy: FetchPolicy.networkOnly,
 errorPolicy: ErrorPolicy.ignore,
 cacheRereadPolicy: CacheRereadPolicy.ignoreAll,

It works.

**Comment by micimize** [comment]
@AneesRazaRaise that is bizarre / seems unlikely to be the root problem, as the client itself shouldn't touch graphql errors. Try running your query with / without __typename via another client such as graphiql

**Comment by budde377** [comment]
This issue seems stale. Closing for now.
