### ISSUE TITLE
Graphql not initialized in get_it

### ISSUE THREAD

**Issue by Aminul-Haque-Aome** [zino-hofmann/graphql-flutter#927]
I want to implement GraphQL client in my flutter app. For Dependency injection, I use GetIt library. But when I run the app, it says

> **Invalid argument (Object of type HomeGraphQLService is not registered inside GetIt. Did you forget to pass an instance name? (Did you accidentally do GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;)): HomeGraphQLService**

Session.dart
```
abstract class Session {
  String getAccessToken();
}
```

SessionImpl.dart
```
class SessionImpl extends Session {
  SharedPreferences sharedPref;

  SessionImpl(SharedPreferences sharedPref) {
    this.sharedPref = sharedPref;
  }

  @override
  String getAccessToken() {
    return sharedPref.getString('access_token') ?? "";
  }

}
```

GraphQLClientGenerator.dart
```
class GraphQLClientGenerator {
  Session session;

  GraphQLClientGenerator(Session session) {
    this.session = session;
  }

  GraphQLClient getClient() {
    final HttpLink httpLink = HttpLink('https://xxx/graphql');
    final AuthLink authLink = AuthLink(getToken: () async => 'Bearer ${_getAccessToken()}');
    final Link link = authLink.concat(httpLink);

    return GraphQLClient(link: link, cache: GraphQLCache(store: InMemoryStore()));
  }

  String _getAccessToken() {
    return session.getAccessToken();
  }
}
```

ServiceLocator.dart
```
Future<void> initDependencies() async {
  await _initSharedPref();
  _initSession();
  _initGraphQLClient();
  _initGraphQLService();
}

Future<void> _initSharedPref() async {
  SharedPreferences sharedPref = await SharedPreferences.getInstance();
  serviceLocator.registerSingleton<SharedPreferences>(sharedPref);
}

void _initSession() {
  serviceLocator.registerLazySingleton<Session>(()=>SessionImpl(serviceLocator()));
}

void _initGraphQLClient() {
  serviceLocator.registerLazySingleton<GraphQLClient>(() => GraphQLClientGenerator(serviceLocator()).getClient());
}

void _initGraphQLService() {
  serviceLocator.registerLazySingleton<HomeGraphQLService>(() => HomeGraphQLService(serviceLocator()));
}
```

main.dart
```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  SystemChrome.setPreferredOrientations(
    [DeviceOrientation.portraitUp, DeviceOrientation.portraitDown],
  );
  
  await initDependencies();

  runApp(MyApp());
}
```

**Comment by KammererTob** [comment]
I feel like this question does not belong into this repository, since it is most likely an issue with implementation or `GetIt`. 
What is `serviceLocator`, and how do you try to access it later in your code?

**Comment by Aminul-Haque-Aome** [comment]
> I feel like this question does not belong into this repository, since it is most likely an issue with implementation or `GetIt`.
> What is `serviceLocator`, and how do you try to access it later in your code?

Actually, I am confused. Cause all the other object which is registered inside GetIt are working perfectly. But only GraphQL not initialized although I registered it inside GetIt. That's why I didn't get any clue to solve this problem

**Comment by KammererTob** [comment]
Can you share your `serviceLocator` and also the code where the error is thrown?

**Comment by budde377** [comment]
This issue seems to be stale. Closing for now.
