### ISSUE TITLE
FetchMore order after re-fetching from cache

### ISSUE THREAD

**Issue by steebchen** [zino-hofmann/graphql-flutter#931]
I'm using fetchMore, and it works fine, but when I do another query somewhere else after fetchMore has been executed a few times, the most recent data is returned, but I want that query to return the initial data. For example:

```
-> user navigates to /dashboard to show most crucial todo items
-> with fetch policy of cacheFirst for better UX
client.query(..) // fetch todo items 1, 2, 3

-> user navigates to /todos and scrolls through list

fetchMore() // fetches 1, 2, 3
fetchMore() // fetches 4, 5, 6
fetchMore() // fetches 7, 8, 9

-> user navigates back to /dashboard

client.query(..) // returns // 7, 8, 9
```

Is there a way to get back the initial data (1, 2, 3) in this call? I've tried different combinations of FetchMoreOptions and FetchMoreOptions.partial and tried switching next/prev around, but one seems to do the wrong thing (showing 1, 2, 3 in the pagination over and over again), and the other has the behaviour above.

Any help would be highly appreciated, thanks!

**Comment by budde377** [comment]
A way to resolve this is not to rely on the query data solely for pagination. Instead, as you fetch more data, append it to the existing data. Then, use some state in your widget to keep track of the current page and use this to hide the data you don't want to show. 

From your example, 

 ```
-> user navigates to /dashboard to show most crucial todo items
-> with fetch policy of cacheFirst for better UX
client.query(..) // fetch todo items [1, 2, 3] -> the result contains [1, 2, 3]

-> user navigates to /todos and scrolls through list

fetchMore() // fetches 4, 5, 6 -> the result contains [1, 2, 3, 4, 5, 6]
fetchMore() // fetches 7, 8, 9 -> the result contains [1, 2, 3, 4, 5, 6, 7, 8, 9]

-> user navigates back to /dashboard

client.query(..) // returns [1, 2, 3, 4, 5, 6, 7, 8, 9], you only render [1, 2, 3]
```
