### ISSUE TITLE
Switches don't work

### ISSUE THREAD

**Issue by asmodeoux** [zino-hofmann/graphql-flutter#933]
**Describe the issue**
I upgraded the project to null-safety and upgraded the libraries to the newest versions. After that GraphQL stopped working correctly. It doesn't operate queries with switch signs (...) now.

Here is the API response I receive:
`responseString: {
                "data": {
                  "user": {
                    "id": 409,
                    "info": {
                      "email": "yuri.goncharenko@diversido.io",
                      "firstName": "Yuri",
                      "lastName": "Goncharenko",
                      "avatar": "https://lh3.googleusercontent.com/a-/AOh14Gjv2BpAeTxGyhC9cupGeDFAjJb14taGAV1dznxZ=s96-c",
                      "phone": "+79118248658"
                    },
                    "roles": [
                      {
                        "id": 186,
                        "role": "client",
                        "myFitnessPalId": null
                      }
                    ],
                    "chatJwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImN0eSI6InR3aWxpby1mcGE7dj0xIn0.eyJqdGkiOiJTSzcyNGE0ZDM3YjEzN2FmNzI4NzkzOTVkYmFhMTlmMTEzLTE2MjU4MTg2ODgiLCJncmFudHMiOnsiaWRlbnRpdHkiOiJ1c2VyLTQwOSIsImNoYXQiOnsic2VydmljZV9zaWQiOiJJU2I2NGY2YzE4ZGQ4MjQ0ODE4NjlmZmIwNjlmZWVjZWYwIn19LCJpYXQiOjE2MjU4MTg2ODgsImV4cCI6MTYyNTgyMjI4OCwiaXNzIjoiU0s3MjRhNGQzN2IxMzdhZjcyODc5Mzk1ZGJhYTE5ZjExMyIsInN1YiI6IkFDOWNmNzA5YTgzMDliNDNhODE3MjAzYjI1ZjViNWU4NjEifQ.fwCixgymBBN99xbrbpkh5wyUx8wlmlCB9wJoasufP4w"
                  }
                }
              },
                    statusCode: 200,`

Here is the query model:
`query {
  user {
    id
    info {
      ...UserInfoFragment
    }
    roles {
      ... on Client {
        ...RoleUserFragment
        myFitnessPalId
      }
      ... on Coach {
        ...RoleUserFragment
        maxActiveClients
        inviteCode
      }
    }
    chatJwt
  }
}`

And here is how it's being parsed:
`{user: {id: 409, info: null, roles: [null], chatJwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImN0eSI6InR3aWxpby1mcGE7dj0xIn0.eyJqdGkiOiJTSzcyNGE0ZDM3YjEzN2FmNzI4NzkzOTVkYmFhMTlmMTEzLTE2MjU4MTg2ODgiLCJncmFudHMiOnsiaWRlbnRpdHkiOiJ1c2VyLTQwOSIsImNoYXQiOnsic2VydmljZV9zaWQiOiJJU2I2NGY2YzE4ZGQ4MjQ0ODE4NjlmZmIwNjlmZWVjZWYwIn19LCJpYXQiOjE2MjU4MTg2ODgsImV4cCI6MTYyNTgyMjI4OCwiaXNzIjoiU0s3MjRhNGQzN2IxMzdhZjcyODc5Mzk1ZGJhYTE5ZjExMyIsInN1YiI6IkFDOWNmNzA5YTgzMDliNDNhODE3MjAzYjI1ZjViNWU4NjEifQ.fwCixgymBBN99xbrbpkh5wyUx8wlmlCB9wJoasufP4w}}`

I think the problem is somewhere in this library, correct me if I'm wrong.

**To Reproduce**
1. Make a query with switch logic
2. Try to get the response JSON
3. See that it's being parsed wrong

**Expected behavior**
Expected behaviour is to get the response parsed correctly

**device / execution context**
Any, mostly tested on Android

### Other useful/optional fields

**Flutter doctor**
`[✓] Flutter (Channel stable, 2.2.3, on macOS 11.3.1 20E241 darwin-arm, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.58.0)
[✓] Connected device (2 available)
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)`

**pubspec.yaml**
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  graphql_flutter: ^5.0.0
  dio: ^4.0.0
  connectivity_plus: ^1.0.4

  json_annotation: ^4.0.1
  shared_preferences: ^2.0.6
  package_info: ^2.0.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  collection: ^1.14.13
  permission_handler: ^8.1.2

  redux: ^5.0.0
  flutter_redux: ^0.8.2
  redux_epics: ^0.15.0
  redux_logging: ^0.5.0
  redux_persist: ^0.9.0
  redux_persist_flutter: ^0.9.0

  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0
  firebase_auth_web: ^2.0.0
  google_sign_in: ^5.0.4
  sign_in_with_apple: ^3.0.0
  flutter_facebook_auth: ^3.5.0
  firebase_analytics: ^8.1.2
  firebase_crashlytics: ^2.0.7
  firebase_performance: ^0.7.0
  logger: ^0.9.4
  crypto: ^3.0.1
  device_info: ^2.0.2
  uuid: ^3.0.4
  image_picker: ^0.8.1+3

  rxdart: ^0.26.0
  equatable: ^2.0.3

  flutter_localizations:
    sdk: flutter

  timezone: ^0.7.0
  flutter_native_timezone: 1.0.10

  get_it: ^7.1.4

  flutter_svg: ^0.22.0
  cupertino_icons: ^1.0.0
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.0.9
  flutter_styled_toast: ^2.0.0
  keyboard_actions: ^3.3.1+1
  flutter_link_preview: ^1.5.6
  cached_network_image: ^3.0.0

  flutter_local_notifications: ^6.0.0
  background_fetch: ^1.0.1

  app_settings: ^4.1.0

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  build: ^2.0.0
  path_provider: ^2.0.2
  http: ^0.13.3
  http_parser: ^4.0.0
  gql: ^0.13.0
  glob: ^2.0.0
  dart_style: ^2.0.0
  yaml: ^3.0.0
  code_builder: ^4.0.0
  args: ^2.0.0
  plugin_platform_interface: ^2.0.0
  xml: ^5.0.0
  built_collection: ^5.0.0
  firebase_auth_platform_interface: ^5.0.0
  google_sign_in_platform_interface: ^2.0.1
  device_info_platform_interface: ^2.0.1
  url_launcher_platform_interface: ^2.0.4
  permission_handler_platform_interface: ^3.6.0
  html: ^0.15.0
  path_drawing: ^0.5.1
  image_picker_platform_interface: ^2.1.0
  enum_to_string: ^2.0.1
  csslib: ^0.17.0
  path_parsing: ^0.2.1
  flutter_local_notifications_platform_interface: ^4.0.0
  async: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.3
  pedantic: ^1.0.0
  build_runner: ^2.0.2
  rename: ^1.2.0
  flutter_launcher_icons: ^0.9.0
  gql_code_gen: ^0.2.0-alpha.1
  hive_generator: ^1.1.0

flutter:
  generate: true

**Comment by budde377** [comment]
This seems to be related to fragments. Please try and update to the latest beta version and ensure you have the right setup (see [README](https://github.com/zino-hofmann/graphql-flutter/tree/beta/packages/graphql#normalization))
