### ISSUE TITLE
Query with police 'cacheAndNetwork' always` uses the network without the cache

### ISSUE THREAD

**Issue by KubanychAsanov** [zino-hofmann/graphql-flutter#939]
**Flutter graphql using cache with hive, when calling query with police 'cacheAndNetwork' it always uses the network without the cache.**

**Here is my GraphQL client**
```
 GraphQLClient _client;
  Client httpClient;

  void initClient(session) {
    if (_client != null) return;

    final token = session.getAccessToken().getJwtToken();

    final HttpLink _httpLink = HttpLink(
      'https://*************/graphql',
      defaultHeaders: {
        'x-api-key': '************',
        'Content-Type': '*************'
      },
      httpClient: this.httpClient,
    );

    final AuthLink _authLink = AuthLink(getToken: () => token);

    final Link _link = _authLink.concat(_httpLink);

    _client = GraphQLClient(
      cache: GraphQLCache(
        store: HiveStore(),
      ),
      link: _link,
    );
  }
```
**Here is my query**
```
Future<QueryResult> query(String query,
      {Map<String, dynamic> variables}) async {
    QueryOptions options = QueryOptions(
      document: gql(query),
      variables: variables,
      fetchPolicy: FetchPolicy.cacheAndNetwork,
      errorPolicy: ErrorPolicy.none,
      cacheRereadPolicy: CacheRereadPolicy.mergeOptimistic,
    );

    final result = await _client.query(options);

    return result;
  }
```

**Problem**
If I change fetchPolicy to cacheOnly or cacheFirst it using cache perfectly, but when DB updated it still showing old data that is why I want to use  cacheAndNetwork.
But how I described it works like a networkOnly what is the ERROR, I don't know why?
Can someone help me or fix the bug if its package bug?

Question at [stackOwerflow](https://stackoverflow.com/questions/68266726/flutter-graphql-using-cache-with-hive-when-calling-query-with-police-cacheandn)

**Comment by saahilmehra** [comment]
@vincenzopalazzo Any update on this issue?

**Comment by vincenzopalazzo** [comment]
> @vincenzopalazzo Any update on this issue?

Not yet, where are trying to give more priority to bugs that we can see and reproduce, if you can reproduce this bug we can put for version 5.1.0

**Comment by saahilmehra** [comment]
> > @vincenzopalazzo Any update on this issue?
> 
> Not yet, where are trying to give more priority to bugs that we can see and reproduce, if you can reproduce this bug we can put for version 5.1.0

Yes, I am also facing same issue and hence can be reproduced. Let me know how can I help?

**Comment by vincenzopalazzo** [comment]
>Yes, I am also facing same issue and hence can be reproduced. Let me know how can I help?

If you can make a reproducible example, could be great.

Thanks!

**Comment by saahilmehra** [comment]
> > Yes, I am also facing same issue and hence can be reproduced. Let me know how can I help?
> 
> If you can make a reproducible example, could be great.
> 
> Thanks!

Check reproducible example [here](https://github.com/saahilmehra/Graphql-Demo).

**Comment by vincenzopalazzo** [comment]
Put in my todo list, thanks

**Comment by KubanychAsanov** [comment]
Thanks guys, good job! Issue opened on 16 jul, 2021 :)
