### ISSUE TITLE
data:"null" cache overrides valid response

### ISSUE THREAD

**Issue by Nazacheres** [zino-hofmann/graphql-flutter#942]
**Describe the issue**
On every network-only request, the response is always `data:null`. 
The response actually arrives but at that point
https://github.com/zino-app/graphql-flutter/blob/2e11ce443127f1705e2b883cd87de746bad54f6b/packages/graphql/lib/src/core/_query_write_handling.dart#L116
It gets overridden with `data:null`.

**To Reproduce**
* Any Query
* Version 5.0.0
* Exactly the same code base works fine with 5.0.0-nullsafety.2
* Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
* Framework • revision f4abaa0735 (3 weeks ago) • 2021-07-01 12:46:11 -0700
* Engine • revision 241c87ad80
* Tools • Dart 2.13.4

**device / execution context**
iOS/Android/Web

**Comment by Nealsoni00** [comment]
I experienced this issue before -- try to explicitly set the query to ignore optimistic results. I moved to `Ferry` since they have a better caching system imo (with a lot stronger typing) and had a lot less issues off the bat.

**Comment by budde377** [comment]
Please provide a minimal reproducible example.
