### ISSUE TITLE
Add onCompleted and onError callbacks to QueryOptions

### ISSUE THREAD

**Issue by paoloposo** [zino-hofmann/graphql-flutter#954]
**Is your feature request related to a problem? Please describe.**
I'm looking for a way to do an action once when a query is completed using the `Query` widget. The action should not be repeated on subsequent calls of the `build` function. See below for a more concrete example.

**Describe the solution you'd like**
The `QueryOptions` class should accept `onCompleted` and `onError` function handlers, just like the `MutationOptions` class does.

**Describe alternatives you've considered**
I've considered writing my own Flutter wrapper for the `graphql` package, bypassing the `graphql_flutter` package altogether. Obviously, I'd like to avoid that.

**Additional context**
Here is an example. Suppose I have a `StatefulWidget` like so:

```dart
Widget build(BuildContext context) {

    return Query(
      options: QueryOptions(
        document: gql('...'),
      ),
      build: (result, { refetch, fetchMore }) {
        
        controller.value = result.data['...'];
        
        if (result.isLoading) return CircularProgressIndicator();
        else if (result.hasException) return Text('Error');
        else {
          return Text(controller.value);
        }
      },
    );
```

When the query is completed, I want to populate the controller's value with some part of the result. The controller's value may change due to user interaction. Later, the user may decide to save the changes, upon which a mutation is triggered (this is not the problematic part).

The problem is, since the controller value is set in the `build` function, its value gets reset everytime the widget is rebuilt, which is not intended. Instead, it would be useful to be able to write this:

```dart
Widget build(BuildContext context) {

    return Query(
      options: QueryOptions(
        document: gql('...'),
        onCompleted: (result) {
          controller.value = result.data['...'];
        },
      ),
      build: (result, { refetch, fetchMore }) {
        if (result.isLoading) return CircularProgressIndicator();
        else if (result.hasException) return Text('Error');
        else {
          return Text(controller.value);
        }
      },
    );
  }
```

**Comment by vasilich6107** [comment]
@paoloposo 
No active maintainer for now
https://github.com/zino-app/graphql-flutter/issues/894

**Comment by fabis94** [comment]
I'm also very interested in this, I don't think you can do proper error handling without this feature.

I'd be open to do a PR with this, if there's a chance it could get released somewhat quickly :)

**Comment by budde377** [comment]
A pr is highly appreciated and we're actively realising contributions
