### ISSUE TITLE
Investigate the ResponseFormatException

### ISSUE THREAD

**Issue by ldemyanenko** [zino-hofmann/graphql-flutter#956]
I'm getting ResponseFormatException during the query call.
Simple query without params.

I/flutter (29070): api fetchCurrentUser errors: OperationException(linkException: ResponseFormatException(originalException: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>?' in type cast), graphqlErrors: [])

Is this a client side parsing issue? If yes, so how can I see what was the server response and where was the problem?

**Comment by vasilich6107** [comment]
Run the query in Postman to see what it returns.
You are not giving any information to help you.
The better you can do is to prepare reproduction demo

**Comment by vincenzopalazzo** [comment]
Marked this issue as outdated.

Feel free to open it again with a reproducible example.
