### ISSUE TITLE
feat(cache): delete a single entity and broadcast

### ISSUE THREAD

**Issue by jjangga0214** [zino-hofmann/graphql-flutter#965]
**Is your feature request related to a problem? Please describe.**

Let's say I have a type `Foo`, and it's used by many queries, like an example below

```graphql
type Foo {
  id: ID!
  bar: String
}

type Query {
  getFoos: [Foo]
  getSpeicalFoos:[Foo] 
  getMyFoos: [Foo]
  # ... and so on
}

Mutation {
  deleteFoo(id: ID!): Foo
}
```

My views use many queries with many foo entities.
And if I click a button, it deletes a single entity from database.

So I want to delete the exact entity from the cache, and broadcast this removal to every query which gets `Foo` as a response.

Currently, it seems not possible, but I believe that'd be so convenient.

**Describe the solution you'd like**

Something like this.

```dart
update: (cache, result) {
  // This would be automatically broadcasted.
  cache.delete(idFields: {
      '__typename': 'Foo',
      'id': '3h34lk5lj6',
     },
  );                                          }
}
```

**Describe alternatives you've considered**

**Additional context**

**Comment by tynn** [comment]
This goes both ways:

- deleted entries are kept in cached query
- newly inserted entries are not added to the cached query

As a workaround I delete it manually from the cache

    client.cache.store.delete('$typename:$id');

But you might need to handle the rebroadcast manually as well

    client.queryManager.maybeRebroadcastQueries(force: true);

**Comment by biklas7** [comment]
> As a workaround I delete it manually from the cache
> 
> ```
> client.cache.store.delete('$typename:$id');
> ```
> 
> But you might need to handle the rebroadcast manually as well
> 
> ```
> client.queryManager.maybeRebroadcastQueries(force: true);
> ```

This stopped working on the latest beta version FYI @vincenzopalazzo
