### ISSUE TITLE
feat(api): refetch every query associated with specific type

### ISSUE THREAD

**Issue by jjangga0214** [zino-hofmann/graphql-flutter#966]
**Is your feature request related to a problem? Please describe.**

Let's say I have a type `Foo`, and it's used by many queries, like an example below

```graphql
type Foo {
  id: ID!
  bar: String
}

type Query {
  getFoos: [Foo]
  getSpeicalFoos:[Foo] 
  getMyFoos: [Foo]
  # ... and so on
}

Mutation {
  insertFoo(bar: String): Foo
}
```

My views use many queries with many foo entities.
And if I click a button, it inserts a single entity into the database.

I want to automatically refetch every query that relies on `Foo`.

Currently, it seems not possible, but I believe that'd be so convenient.

**Describe the solution you'd like**

Something like this.

```dart
update: (cache, result) {
  // This refetches `getFoos`, `getSpeicalFoos`, `getMyFoos` without explicitly specifiying them
  cache.refetchQueriesRelyingOn(typename: 'Foo');
}
```

**Describe alternatives you've considered**

**Additional context**

**Comment by budde377** [comment]
Realistically, I don't think this is something that's best handled generally by the framework, rather specifically by your use case on your end. Blindless fetching of arbitrary queries will be a nightmare to debug. Instead, I'd propose that you

* **Look at your architecture.** Can my schema be orchestrated in a better way to propagate these changes?
* **Add a custom refresh query**. You can add a query with the sole intention of refetching after a `Foo` has been added. You can then call this with `client.query(...)` which'll update the cache.
