### ISSUE TITLE
Different responses on different versions of the library

### ISSUE THREAD

**Issue by zhenyakr** [zino-hofmann/graphql-flutter#967]
Previously used version 3.1.0, decided to upgrade to the current version.
Faced with the fact that I get a different response than the one I have and which I have on the backend in GraphQL

This is my normal answer in GraphQL:
![image](https://user-images.githubusercontent.com/8798011/135441314-2d09cb7a-85a3-462d-a502-14e5a78e67e7.png)

And this is my broken response: 
![image](https://user-images.githubusercontent.com/8798011/135441591-726cacfe-1457-458c-aa9e-6947c626bfc6.png)

The difference is that some fields have changed very strangely. I do not know how to explain it but when I run the same code on version 3.1.0, I get a normal answer

This is my graphql client initialization on version 5.0.0
![image](https://user-images.githubusercontent.com/8798011/135441813-e199f5d1-eb80-4171-91df-9a288c2c3759.png)

And this is my graphql client initialization on version 3.1.0
![image](https://user-images.githubusercontent.com/8798011/135442046-44654bc2-2d2d-449c-aa3d-994cd9d6745e.png)

I hope you can explain to me what's going on
Thanks!

**Comment by vincenzopalazzo** [comment]
HI @zhenyakr, can you provide an example that returns two types of responses?

In addition, from 3.1.0 to 5.x.x there are two major versions of differences, this usually it fine has some deprecation long the way, for this reason, it is suggested always to work with the last version of one library.

**Comment by budde377** [comment]
Closing this because of lack of response from the author.
