### ISSUE TITLE
With latest gql_exec version, the package graphql and its tests don't compile

### ISSUE THREAD

**Issue by Pacane** [zino-hofmann/graphql-flutter#990]
**Describe the issue**
gql_exec introduced a breaking change in 0.3.1 (a patch version) and when you pub upgrade to 0.3.1, projects depending on graphql don't compile anymore.

**To Reproduce**
bump gql_exec to ^0.3.1 in pubspec.yaml

and it won't compile graphql+its tests.

### Other useful/optional fields

They added a required `response` field to the `Response` const constructor. Not sure what we should put in our case.

**screenshots**
![image](https://user-images.githubusercontent.com/2762440/144263027-6466ca95-4ff9-420b-9c15-a0ea4b81cb2f.png)

It seems, that we'd also need to bump `gql_link` to `^0.4.1` as well. I went ahead in my own fork and also updated the other gql_* dependencies.

**Comment by vincenzopalazzo** [comment]
Fixed with https://github.com/zino-hofmann/graphql-flutter/pull/999 and I'm preparing a new version beta.

Feedback are welcome :)
